-- v107 (JCN sync 2026-06-26) — colunas que o painel adicionou em tabelas compartilhadas.
-- add column if not exists (idempotente; NOT NULL só com default). Aplicado via MCP supabase-sst.
alter table public.acoes_5w2h add column if not exists id_apreciacao_acao text;
alter table public.aep_relatorios add column if not exists data_validade date;
alter table public.aet_relatorios add column if not exists created_at timestamptz default now() not null;
alter table public.aet_relatorios add column if not exists data_elaboracao date;
alter table public.aet_relatorios add column if not exists data_validade date;
alter table public.aet_relatorios add column if not exists endereco_empresa text default ''::text;
alter table public.aet_relatorios add column if not exists id_relatorio uuid default gen_random_uuid() not null;
alter table public.aet_relatorios add column if not exists registro_profissional text default ''::text not null;
alter table public.aet_relatorios add column if not exists responsavel_elaboracao text default ''::text not null;
alter table public.aet_relatorios add column if not exists status text default 'RASCUNHO'::text not null;
alter table public.aet_relatorios add column if not exists titulo_profissional text default ''::text not null;
alter table public.aet_relatorios add column if not exists updated_at timestamptz;
alter table public.aet_relatorios add column if not exists usuario uuid;
alter table public.analises_quimicos add column if not exists data_validade date;
alter table public.apreciacoes_maquinas add column if not exists componentes_maquina text[] default '{}'::text[];
alter table public.apreciacoes_maquinas add column if not exists data_validade date;
alter table public.apreciacoes_maquinas add column if not exists id_inspecao text;
alter table public.apreciacoes_maquinas add column if not exists limite_espaco text;
alter table public.apreciacoes_maquinas add column if not exists limite_produtividade text;
alter table public.apreciacoes_maquinas add column if not exists limite_tempo text;
alter table public.apreciacoes_maquinas add column if not exists limite_uso text;
alter table public.apreciacoes_maquinas add column if not exists npe text;
alter table public.apreciacoes_maquinas add column if not exists sistemas_atual text[] default '{}'::text[];
alter table public.apreciacoes_maquinas add column if not exists sistemas_necessario text[] default '{}'::text[];
alter table public.drps_relatorios add column if not exists agravos_saude_mental text;
alter table public.drps_relatorios add column if not exists conclusao_geral text;
alter table public.drps_relatorios add column if not exists data_validade date;
alter table public.empresas add column if not exists bairro text;
alter table public.empresas add column if not exists cep text;
alter table public.empresas add column if not exists cnae_descricao text;
alter table public.empresas add column if not exists cnae_principal text;
alter table public.empresas add column if not exists complemento text;
alter table public.empresas add column if not exists email text;
alter table public.empresas add column if not exists id_unidade text;
alter table public.empresas add column if not exists logradouro text;
alter table public.empresas add column if not exists municipio text;
alter table public.empresas add column if not exists numero text;
alter table public.empresas add column if not exists porte text;
alter table public.empresas add column if not exists situacao_cadastral text;
alter table public.empresas add column if not exists telefone text;
alter table public.empresas add column if not exists uf text;
alter table public.inspecoes add column if not exists data_validade date;
alter table public.inspecoes add column if not exists elaboracao_concluida_em timestamptz;
alter table public.inspecoes add column if not exists elaboracao_responsavel text;
alter table public.inspecoes add column if not exists elaboracao_status text;
alter table public.riscos add column if not exists foto_quim_url text;
alter table public.usuarios add column if not exists certificado_titular text;
alter table public.usuarios add column if not exists certificado_validade timestamptz;
alter table public.usuarios add column if not exists unidades text[] default '{}'::text[] not null;
