-- ============================================================
-- v144 (SST-JCN) — Grau de risco automatico a partir do CNAE (NR-4, Anexo I)
-- Espelha o painel-sst v141 (dado universal da NR-4, copiado byte-a-byte).
-- Aplicacao: schema/funcao/RLS via MCP; os 673 registros carregados via script
-- (parse deste arquivo) e verificados por md5 identico ao arquivo. Idempotente.
-- ============================================================
-- O grau de risco nao e opiniao: e consulta em tabela. O Anexo I da NR-4
-- da, para cada classe CNAE, o grau de 1 a 4. Como a busca por CNPJ ja
-- traz o CNAE da Receita, o grau pode ser derivado sem digitacao.
--
-- FONTE (unica autorizada, indicada pelo usuario em 22/07/2026):
--   NR-4 atualizada 2023, Anexo I — "RELACAO DA CLASSIFICACAO NACIONAL DE
--   ATIVIDADES ECONOMICAS - CNAE (VERSAO 2.0), COM CORRESPONDENTE GRAU DE
--   RISCO - GR"
--   https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-04-atualizada-2023.pdf
--
-- COMO ESTES DADOS FORAM OBTIDOS: extraidos do PDF por dois metodos
-- independentes (pdftotext -layout e pdftotext -raw, com leitores
-- diferentes), que concordaram nos 673 mapeamentos. O total bate com as
-- 673 classes da CNAE 2.0. Nenhum valor foi digitado a mao.
--
-- GRANULARIDADE: a norma trabalha na CLASSE (5 digitos, ex. 45.11-1). A
-- Receita devolve a SUBCLASSE (7 digitos, ex. 4511102). A subclasse e a
-- classe + 2 digitos, entao truncar em 5 da a classe. E o que a funcao
-- abaixo faz.
--
-- IMPORTANTE: esta tabela NAO altera nenhum cadastro existente. Ela so
-- responde "o que a norma diz". Quem grava e a tela, com uma pessoa
-- decidindo.
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.cnae_grau_risco (
  cnae_classe  TEXT PRIMARY KEY,
  grau_risco   INT  NOT NULL,
  denominacao  TEXT NOT NULL,
  -- Versionado: quando a NR-4 mudar, entra outra carga e da para saber de
  -- qual texto veio cada linha.
  versao_norma TEXT NOT NULL DEFAULT 'NR-4 (2023) Anexo I / CNAE 2.0',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
BEGIN
  ALTER TABLE public.cnae_grau_risco
    ADD CONSTRAINT cnae_grau_risco_grau_chk CHECK (grau_risco BETWEEN 1 AND 4);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE public.cnae_grau_risco
    ADD CONSTRAINT cnae_grau_risco_classe_chk CHECK (cnae_classe ~ '^[0-9]{5}$');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TABLE public.cnae_grau_risco
  IS 'Anexo I da NR-4 (2023): classe CNAE 2.0 -> grau de risco. Somente leitura pela aplicacao.';

-- Carga idempotente: reaplicar atualiza em vez de duplicar.
INSERT INTO public.cnae_grau_risco (cnae_classe, grau_risco, denominacao) VALUES
  ('01113', 3, 'Cultivo de cereais'),
  ('01121', 3, 'Cultivo de algodão herbáceo e de outras fibras de lavoura temporária'),
  ('01130', 3, 'Cultivo de cana-de-açúcar'),
  ('01148', 3, 'Cultivo de fumo'),
  ('01156', 3, 'Cultivo de soja'),
  ('01164', 3, 'Cultivo de oleaginosas de lavoura temporária, exceto soja'),
  ('01199', 3, 'Cultivo de plantas de lavoura temporária não especificadas anteriormente'),
  ('01211', 3, 'Horticultura'),
  ('01229', 3, 'Cultivo de flores e plantas ornamentais'),
  ('01318', 3, 'Cultivo de laranja'),
  ('01326', 3, 'Cultivo de uva'),
  ('01334', 3, 'Cultivo de frutas de lavoura permanente, exceto laranja e uva'),
  ('01342', 3, 'Cultivo de café'),
  ('01351', 3, 'Cultivo de cacau'),
  ('01393', 3, 'Cultivo de plantas de lavoura permanente não especificadas anteriormente'),
  ('01415', 3, 'Produção de sementes certificadas'),
  ('01423', 3, 'Produção de mudas e outras formas de propagação vegetal, certificadas'),
  ('01512', 3, 'Criação de bovinos'),
  ('01521', 3, 'Criação de outros animais de grande porte'),
  ('01539', 3, 'Criação de caprinos e ovinos'),
  ('01547', 3, 'Criação de suínos'),
  ('01555', 3, 'Criação de aves'),
  ('01598', 3, 'Criação de animais não especificados anteriormente'),
  ('01610', 3, 'Atividades de apoio à agricultura'),
  ('01628', 3, 'Atividades de apoio à pecuária'),
  ('01636', 3, 'Atividades de pós-colheita'),
  ('01709', 3, 'Caça e serviços relacionados'),
  ('02101', 3, 'Produção florestal - florestas plantadas'),
  ('02209', 4, 'Produção florestal - florestas nativas'),
  ('02306', 3, 'Atividades de apoio à produção florestal'),
  ('03116', 3, 'Pesca em água salgada'),
  ('03124', 3, 'Pesca em água doce'),
  ('03213', 3, 'Aqüicultura em água salgada e salobra'),
  ('03221', 3, 'Aqüicultura em água doce'),
  ('05003', 4, 'Extração de carvão mineral'),
  ('06000', 4, 'Extração de petróleo e gás natural'),
  ('07103', 4, 'Extração de minério de ferro'),
  ('07219', 4, 'Extração de minério de alumínio'),
  ('07227', 4, 'Extração de minério de estanho'),
  ('07235', 4, 'Extração de minério de manganês'),
  ('07243', 4, 'Extração de minério de metais preciosos'),
  ('07251', 4, 'Extração de minerais radioativos'),
  ('07294', 4, 'Extração de minerais metálicos não-ferrosos não especificados anteriormente'),
  ('08100', 4, 'Extração de pedra, areia e argila'),
  ('08916', 4, 'Extração de minerais para fabricação de adubos, fertilizantes e outros produtos químicos'),
  ('08924', 4, 'Extração e refino de sal marinho e sal-gema'),
  ('08932', 4, 'Extração de gemas (pedras preciosas e semipreciosas)'),
  ('08991', 4, 'Extração de minerais não-metálicos não especificados anteriormente'),
  ('09106', 4, 'Atividades de apoio à extração de petróleo e gás natural'),
  ('09904', 4, 'Atividades de apoio à extração de minerais, exceto petróleo e gás natural'),
  ('10112', 3, 'Abate de reses, exceto suínos'),
  ('10121', 3, 'Abate de suínos, aves e outros pequenos animais'),
  ('10139', 3, 'Fabricação de produtos de carne'),
  ('10201', 3, 'Preservação do pescado e fabricação de produtos do pescado'),
  ('10317', 3, 'Fabricação de conservas de frutas'),
  ('10325', 3, 'Fabricação de conservas de legumes e outros vegetais'),
  ('10333', 3, 'Fabricação de sucos de frutas, hortaliças e legumes'),
  ('10414', 3, 'Fabricação de óleos vegetais em bruto, exceto óleo de milho'),
  ('10422', 3, 'Fabricação de óleos vegetais refinados, exceto óleo de milho'),
  ('10431', 3, 'Fabricação de margarina e outras gorduras vegetais e de óleos não-comestíveis de animais'),
  ('10511', 3, 'Preparação do leite'),
  ('10520', 3, 'Fabricação de laticínios'),
  ('10538', 3, 'Fabricação de sorvetes e outros gelados comestíveis'),
  ('10619', 3, 'Beneficiamento de arroz e fabricação de produtos do arroz'),
  ('10627', 3, 'Moagem de trigo e fabricação de derivados'),
  ('10635', 3, 'Fabricação de farinha de mandioca e derivados'),
  ('10643', 3, 'Fabricação de farinha de milho e derivados, exceto óleos de milho'),
  ('10651', 3, 'Fabricação de amidos e féculas de vegetais e de óleos de milho'),
  ('10660', 3, 'Fabricação de alimentos para animais'),
  ('10694', 3, 'Moagem e fabricação de produtos de origem vegetal não especificados anteriormente'),
  ('10716', 3, 'Fabricação de açúcar em bruto'),
  ('10724', 3, 'Fabricação de açúcar refinado'),
  ('10813', 3, 'Torrefação e moagem de café'),
  ('10821', 3, 'Fabricação de produtos à base de café'),
  ('10911', 3, 'Fabricação de produtos de panificação'),
  ('10929', 3, 'Fabricação de biscoitos e bolachas'),
  ('10937', 3, 'Fabricação de produtos derivados do cacau, de chocolates e confeitos'),
  ('10945', 3, 'Fabricação de massas alimentícias'),
  ('10953', 3, 'Fabricação de especiarias, molhos, temperos e condimentos'),
  ('10961', 3, 'Fabricação de alimentos e pratos prontos'),
  ('10996', 3, 'Fabricação de produtos alimentícios não especificados anteriormente'),
  ('11119', 3, 'Fabricação de aguardentes e outras bebidas destiladas'),
  ('11127', 3, 'Fabricação de vinho'),
  ('11135', 3, 'Fabricação de malte, cervejas e chopes'),
  ('11216', 3, 'Fabricação de águas envasadas'),
  ('11224', 3, 'Fabricação de refrigerantes e de outras bebidas não-alcoólicas'),
  ('12107', 3, 'Processamento industrial do fumo'),
  ('12204', 3, 'Fabricação de produtos do fumo'),
  ('13111', 3, 'Preparação e fiação de fibras de algodão'),
  ('13120', 3, 'Preparação e fiação de fibras têxteis naturais, exceto algodão'),
  ('13138', 3, 'Fiação de fibras artificiais e sintéticas'),
  ('13146', 3, 'Fabricação de linhas para costurar e bordar'),
  ('13219', 3, 'Tecelagem de fios de algodão'),
  ('13227', 3, 'Tecelagem de fios de fibras têxteis naturais, exceto algodão'),
  ('13235', 3, 'Tecelagem de fios de fibras artificiais e sintéticas'),
  ('13308', 3, 'Fabricação de tecidos de malha'),
  ('13405', 3, 'Acabamentos em fios, tecidos e artefatos têxteis'),
  ('13511', 3, 'Fabricação de artefatos têxteis para uso doméstico'),
  ('13529', 3, 'Fabricação de artefatos de tapeçaria'),
  ('13537', 3, 'Fabricação de artefatos de cordoaria'),
  ('13545', 3, 'Fabricação de tecidos especiais, inclusive artefatos'),
  ('13596', 3, 'Fabricação de outros produtos têxteis não especificados anteriormente'),
  ('14118', 2, 'Confecção de roupas íntimas'),
  ('14126', 2, 'Confecção de peças do vestuário, exceto roupas íntimas'),
  ('14134', 2, 'Confecção de roupas profissionais'),
  ('14142', 2, 'Fabricação de acessórios do vestuário, exceto para segurança e proteção'),
  ('14215', 2, 'Fabricação de meias'),
  ('14223', 2, 'Fabricação de artigos do vestuário, produzidos em malharias e tricotagens, exceto meias'),
  ('15106', 3, 'Curtimento e outras preparações de couro'),
  ('15211', 2, 'Fabricação de artigos para viagem, bolsas e semelhantes de qualquer material'),
  ('15297', 2, 'Fabricação de artefatos de couro não especificados anteriormente'),
  ('15319', 3, 'Fabricação de calçados de couro'),
  ('15327', 3, 'Fabricação de tênis de qualquer material'),
  ('15335', 3, 'Fabricação de calçados de material sintético'),
  ('15394', 3, 'Fabricação de calçados de materiais não especificados anteriormente'),
  ('15408', 3, 'Fabricação de partes para calçados, de qualquer material'),
  ('16102', 3, 'Desdobramento de madeira'),
  ('16218', 3, 'Fabricação de madeira laminada e de chapas de madeira compensada, prensada e aglomerada'),
  ('16226', 3, 'Fabricação de estruturas de madeira e de artigos de carpintaria para construção'),
  ('16234', 3, 'Fabricação de artefatos de tanoaria e de embalagens de madeira'),
  ('16293', 3, 'Fabricação de artefatos de madeira, palha, cortiça, vime e material trançado não especificados anteriormente, exceto móveis'),
  ('17109', 3, 'Fabricação de celulose e outras pastas para a fabricação de papel'),
  ('17214', 3, 'Fabricação de papel'),
  ('17222', 3, 'Fabricação de cartolina e papel-cartão'),
  ('17311', 2, 'Fabricação de embalagens de papel'),
  ('17320', 2, 'Fabricação de embalagens de cartolina e papel-cartão'),
  ('17338', 2, 'Fabricação de chapas e de embalagens de papelão ondulado'),
  ('17419', 2, 'Fabricação de produtos de papel, cartolina, papel-cartão e papelão ondulado para uso comercial e de escritório'),
  ('17427', 2, 'Fabricação de produtos de papel para usos doméstico e higiênico-sanitário'),
  ('17494', 2, 'Fabricação de produtos de pastas celulósicas, papel, cartolina, papel-cartão e papelão ondulado não especificados anteriormente'),
  ('18113', 3, 'Impressão de jornais, livros, revistas e outras publicações periódicas'),
  ('18121', 3, 'Impressão de material de segurança'),
  ('18130', 3, 'Impressão de materiais para outros usos'),
  ('18211', 3, 'Serviços de pré-impressão'),
  ('18229', 3, 'Serviços de acabamentos gráficos'),
  ('18300', 3, 'Reprodução de materiais gravados em qualquer suporte'),
  ('19101', 3, 'Coquerias'),
  ('19217', 3, 'Fabricação de produtos do refino de petróleo'),
  ('19225', 3, 'Fabricação de produtos derivados do petróleo, exceto produtos do refino'),
  ('19314', 3, 'Fabricação de álcool'),
  ('19322', 3, 'Fabricação de biocombustíveis, exceto álcool'),
  ('20118', 3, 'Fabricação de cloro e álcalis'),
  ('20126', 3, 'Fabricação de intermediários para fertilizantes'),
  ('20134', 3, 'Fabricação de adubos e fertilizantes'),
  ('20142', 3, 'Fabricação de gases industriais'),
  ('20193', 3, 'Fabricação de produtos químicos inorgânicos não especificados anteriormente'),
  ('20215', 3, 'Fabricação de produtos petroquímicos básicos'),
  ('20223', 3, 'Fabricação de intermediários para plastificantes, resinas e fibras'),
  ('20291', 3, 'Fabricação de produtos químicos orgânicos não especificados anteriormente'),
  ('20312', 3, 'Fabricação de resinas termoplásticas'),
  ('20321', 3, 'Fabricação de resinas termofixas'),
  ('20339', 3, 'Fabricação de elastômeros'),
  ('20401', 3, 'Fabricação de fibras artificiais e sintéticas'),
  ('20517', 3, 'Fabricação de defensivos agrícolas'),
  ('20525', 3, 'Fabricação de desinfetantes domissanitários'),
  ('20614', 3, 'Fabricação de sabões e detergentes sintéticos'),
  ('20622', 3, 'Fabricação de produtos de limpeza e polimento'),
  ('20631', 2, 'Fabricação de cosméticos, produtos de perfumaria e de higiene pessoal'),
  ('20711', 3, 'Fabricação de tintas, vernizes, esmaltes e lacas'),
  ('20720', 3, 'Fabricação de tintas de impressão'),
  ('20738', 3, 'Fabricação de impermeabilizantes, solventes e produtos afins'),
  ('20916', 3, 'Fabricação de adesivos e selantes'),
  ('20924', 4, 'Fabricação de explosivos'),
  ('20932', 3, 'Fabricação de aditivos de uso industrial'),
  ('20941', 3, 'Fabricação de catalisadores'),
  ('20991', 3, 'Fabricação de produtos químicos não especificados anteriormente'),
  ('21106', 3, 'Fabricação de produtos farmoquímicos'),
  ('21211', 3, 'Fabricação de medicamentos para uso humano'),
  ('21220', 3, 'Fabricação de medicamentos para uso veterinário'),
  ('21238', 3, 'Fabricação de preparações farmacêuticas'),
  ('22111', 3, 'Fabricação de pneumáticos e de câmaras-de-ar'),
  ('22129', 3, 'Reforma de pneumáticos usados'),
  ('22196', 3, 'Fabricação de artefatos de borracha não especificados anteriormente'),
  ('22218', 3, 'Fabricação de laminados planos e tubulares de material plástico'),
  ('22226', 3, 'Fabricação de embalagens de material plástico'),
  ('22234', 3, 'Fabricação de tubos e acessórios de material plástico para uso na construção'),
  ('22293', 3, 'Fabricação de artefatos de material plástico não especificados anteriormente'),
  ('23117', 3, 'Fabricação de vidro plano e de segurança'),
  ('23125', 3, 'Fabricação de embalagens de vidro'),
  ('23192', 3, 'Fabricação de artigos de vidro'),
  ('23206', 4, 'Fabricação de cimento'),
  ('23303', 4, 'Fabricação de artefatos de concreto, cimento, fibrocimento, gesso e materiais semelhantes'),
  ('23419', 4, 'Fabricação de produtos cerâmicos refratários'),
  ('23427', 3, 'Fabricação de produtos cerâmicos não-refratários para uso estrutural na construção'),
  ('23494', 4, 'Fabricação de produtos cerâmicos não-refratários não especificados anteriormente'),
  ('23915', 3, 'Aparelhamento e outros trabalhos em pedras'),
  ('23923', 4, 'Fabricação de cal e gesso'),
  ('23991', 3, 'Fabricação de produtos de minerais não-metálicos não especificados anteriormente'),
  ('24113', 4, 'Produção de ferro-gusa'),
  ('24121', 4, 'Produção de ferroligas'),
  ('24211', 4, 'Produção de semi-acabados de aço'),
  ('24229', 4, 'Produção de laminados planos de aço'),
  ('24237', 4, 'Produção de laminados longos de aço'),
  ('24245', 4, 'Produção de relaminados, trefilados e perfilados de aço'),
  ('24318', 4, 'Produção de tubos de aço com costura'),
  ('24393', 4, 'Produção de outros tubos de ferro e aço'),
  ('24415', 4, 'Metalurgia do alumínio e suas ligas'),
  ('24423', 4, 'Metalurgia dos metais preciosos'),
  ('24431', 4, 'Metalurgia do cobre'),
  ('24491', 4, 'Metalurgia dos metais não-ferrosos e suas ligas não especificados anteriormente'),
  ('24512', 4, 'Fundição de ferro e aço'),
  ('24521', 4, 'Fundição de metais não-ferrosos e suas ligas'),
  ('25110', 4, 'Fabricação de estruturas metálicas'),
  ('25128', 3, 'Fabricação de esquadrias de metal'),
  ('25136', 3, 'Fabricação de obras de caldeiraria pesada'),
  ('25217', 3, 'Fabricação de tanques, reservatórios metálicos e caldeiras para aquecimento central'),
  ('25225', 3, 'Fabricação de caldeiras geradoras de vapor, exceto para aquecimento central e para veículos'),
  ('25314', 4, 'Produção de forjados de aço e de metais não-ferrosos e suas ligas'),
  ('25322', 4, 'Produção de artefatos estampados de metal; metalurgia do pó'),
  ('25390', 4, 'Serviços de usinagem, solda, tratamento e revestimento em metais'),
  ('25411', 3, 'Fabricação de artigos de cutelaria'),
  ('25420', 3, 'Fabricação de artigos de serralheria, exceto esquadrias'),
  ('25438', 3, 'Fabricação de ferramentas'),
  ('25501', 4, 'Fabricação de equipamento bélico pesado, armas de fogo e munições'),
  ('25918', 3, 'Fabricação de embalagens metálicas'),
  ('25926', 4, 'Fabricação de produtos de trefilados de metal'),
  ('25934', 3, 'Fabricação de artigos de metal para uso doméstico e pessoal'),
  ('25993', 3, 'Fabricação de produtos de metal não especificados anteriormente'),
  ('26108', 3, 'Fabricação de componentes eletrônicos'),
  ('26213', 3, 'Fabricação de equipamentos de informática'),
  ('26221', 3, 'Fabricação de periféricos para equipamentos de informática'),
  ('26311', 3, 'Fabricação de equipamentos transmissores de comunicação'),
  ('26329', 3, 'Fabricação de aparelhos telefônicos e de outros equipamentos de comunicação'),
  ('26400', 3, 'Fabricação de aparelhos de recepção, reprodução, gravação e amplificação de áudio e vídeo'),
  ('26515', 3, 'Fabricação de aparelhos e equipamentos de medida, teste e controle'),
  ('26523', 3, 'Fabricação de cronômetros e relógios'),
  ('26604', 3, 'Fabricação de aparelhos eletromédicos e eletroterapêuticos e equipamentos de irradiação'),
  ('26701', 3, 'Fabricação de equipamentos e instrumentos ópticos, fotográficos e cinematográficos'),
  ('26809', 3, 'Fabricação de mídias virgens, magnéticas e ópticas'),
  ('27104', 3, 'Fabricação de geradores, transformadores e motores elétricos'),
  ('27210', 3, 'Fabricação de pilhas, baterias e acumuladores elétricos, exceto para veículos automotores'),
  ('27228', 3, 'Fabricação de baterias e acumuladores para veículos automotores'),
  ('27317', 3, 'Fabricação de aparelhos e equipamentos para distribuição e controle de energia elétrica'),
  ('27325', 3, 'Fabricação de material elétrico para instalações em circuito de consumo'),
  ('27333', 3, 'Fabricação de fios, cabos e condutores elétricos isolados'),
  ('27406', 3, 'Fabricação de lâmpadas e outros equipamentos de iluminação'),
  ('27511', 3, 'Fabricação de fogões, refrigeradores e máquinas de lavar e secar para uso doméstico'),
  ('27597', 3, 'Fabricação de aparelhos eletrodomésticos não especificados anteriormente'),
  ('27902', 3, 'Fabricação de equipamentos e aparelhos elétricos não especificados anteriormente'),
  ('28119', 3, 'Fabricação de motores e turbinas, exceto para aviões e veículos rodoviários'),
  ('28127', 3, 'Fabricação de equipamentos hidráulicos e pneumáticos, exceto válvulas'),
  ('28135', 3, 'Fabricação de válvulas, registros e dispositivos semelhantes'),
  ('28143', 3, 'Fabricação de compressores'),
  ('28151', 3, 'Fabricação de equipamentos de transmissão para fins industriais'),
  ('28216', 3, 'Fabricação de aparelhos e equipamentos para instalações térmicas'),
  ('28224', 3, 'Fabricação de máquinas, equipamentos e aparelhos para transporte e elevação de cargas e pessoas'),
  ('28232', 3, 'Fabricação de máquinas e aparelhos de refrigeração e ventilação para uso industrial e comercial'),
  ('28241', 3, 'Fabricação de aparelhos e equipamentos de ar-condicionado'),
  ('28259', 3, 'Fabricação de máquinas e equipamentos para saneamento básico e ambiental'),
  ('28291', 3, 'Fabricação de máquinas e equipamentos de uso geral não especificados anteriormente'),
  ('28313', 3, 'Fabricação de tratores agrícolas'),
  ('28321', 3, 'Fabricação de equipamentos para irrigação agrícola'),
  ('28330', 3, 'Fabricação de máquinas e equipamentos para a agricultura e pecuária, exceto para irrigação'),
  ('28402', 3, 'Fabricação de máquinas-ferramenta'),
  ('28518', 3, 'Fabricação de máquinas e equipamentos para a prospecção e extração de petróleo'),
  ('28526', 3, 'Fabricação de outras máquinas e equipamentos para uso na extração mineral, exceto na extração de petróleo'),
  ('28534', 3, 'Fabricação de tratores, exceto agrícolas'),
  ('28542', 3, 'Fabricação de máquinas e equipamentos para terraplenagem, pavimentação e construção, exceto tratores'),
  ('28615', 3, 'Fabricação de máquinas para a indústria metalúrgica, exceto máquinas-ferramenta'),
  ('28623', 3, 'Fabricação de máquinas e equipamentos para as indústrias de alimentos, bebidas e fumo'),
  ('28631', 3, 'Fabricação de máquinas e equipamentos para a indústria têxtil'),
  ('28640', 3, 'Fabricação de máquinas e equipamentos para as indústrias do vestuário, do couro e de calçados'),
  ('28658', 3, 'Fabricação de máquinas e equipamentos para as indústrias de celulose, papel e papelão e artefatos'),
  ('28666', 3, 'Fabricação de máquinas e equipamentos para a indústria do plástico'),
  ('28691', 3, 'Fabricação de máquinas e equipamentos para uso industrial específico não especificados anteriormente'),
  ('29107', 3, 'Fabricação de automóveis, camionetas e utilitários'),
  ('29204', 3, 'Fabricação de caminhões e ônibus'),
  ('29301', 3, 'Fabricação de cabines, carrocerias e reboques para veículos automotores'),
  ('29417', 3, 'Fabricação de peças e acessórios para o sistema motor de veículos automotores'),
  ('29425', 3, 'Fabricação de peças e acessórios para os sistemas de marcha e transmissão de veículos automotores'),
  ('29433', 3, 'Fabricação de peças e acessórios para o sistema de freios de veículos automotores'),
  ('29441', 3, 'Fabricação de peças e acessórios para o sistema de direção e suspensão de veículos automotores'),
  ('29450', 3, 'Fabricação de material elétrico e eletrônico para veículos automotores, exceto baterias'),
  ('29492', 3, 'Fabricação de peças e acessórios para veículos automotores não especificados anteriormente'),
  ('29506', 3, 'Recondicionamento e recuperação de motores para veículos automotores'),
  ('30113', 3, 'Construção de embarcações e estruturas flutuantes'),
  ('30121', 3, 'Construção de embarcações para esporte e lazer'),
  ('30318', 3, 'Fabricação de locomotivas, vagões e outros materiais rodantes'),
  ('30326', 3, 'Fabricação de peças e acessórios para veículos ferroviários'),
  ('30415', 3, 'Fabricação de aeronaves'),
  ('30423', 3, 'Fabricação de turbinas, motores e outros componentes e peças para aeronaves'),
  ('30504', 3, 'Fabricação de veículos militares de combate'),
  ('30911', 3, 'Fabricação de motocicletas'),
  ('30920', 3, 'Fabricação de bicicletas e triciclos não-motorizados'),
  ('30997', 3, 'Fabricação de equipamentos de transporte não especificados anteriormente'),
  ('31012', 3, 'Fabricação de móveis com predominância de madeira'),
  ('31021', 3, 'Fabricação de móveis com predominância de metal'),
  ('31039', 3, 'Fabricação de móveis de outros materiais, exceto madeira e metal'),
  ('31047', 2, 'Fabricação de colchões'),
  ('32116', 3, 'Lapidação de gemas e fabricação de artefatos de ourivesaria e joalheria'),
  ('32124', 3, 'Fabricação de bijuterias e artefatos semelhantes'),
  ('32205', 3, 'Fabricação de instrumentos musicais'),
  ('32302', 3, 'Fabricação de artefatos para pesca e esporte'),
  ('32400', 3, 'Fabricação de brinquedos e jogos recreativos'),
  ('32507', 3, 'Fabricação de instrumentos e materiais para uso médico e odontológico e de artigos ópticos'),
  ('32914', 3, 'Fabricação de escovas, pincéis e vassouras'),
  ('32922', 3, 'Fabricação de equipamentos e acessórios para segurança e proteção pessoal e profissional'),
  ('32990', 3, 'Fabricação de produtos diversos não especificados anteriormente'),
  ('33112', 3, 'Manutenção e reparação de tanques, reservatórios metálicos e caldeiras, exceto para veículos'),
  ('33121', 3, 'Manutenção e reparação de equipamentos eletrônicos e ópticos'),
  ('33139', 3, 'Manutenção e reparação de máquinas e equipamentos elétricos'),
  ('33147', 3, 'Manutenção e reparação de máquinas e equipamentos da indústria mecânica'),
  ('33155', 3, 'Manutenção e reparação de veículos ferroviários'),
  ('33163', 3, 'Manutenção e reparação de aeronaves'),
  ('33171', 3, 'Manutenção e reparação de embarcações'),
  ('33198', 3, 'Manutenção e reparação de equipamentos e produtos não especificados anteriormente'),
  ('33210', 3, 'Instalação de máquinas e equipamentos industriais'),
  ('33295', 3, 'Instalação de equipamentos não especificados anteriormente'),
  ('35115', 3, 'Geração de energia elétrica'),
  ('35123', 3, 'Transmissão de energia elétrica'),
  ('35131', 3, 'Comércio atacadista de energia elétrica'),
  ('35140', 3, 'Distribuição de energia elétrica'),
  ('35204', 3, 'Produção de gás; processamento de gás natural; distribuição de combustíveis gasosos por redes urbanas'),
  ('35301', 3, 'Produção e distribuição de vapor, água quente e ar-condicionado'),
  ('36006', 3, 'Captação, tratamento e distribuição de água'),
  ('37011', 3, 'Gestão de redes de esgoto'),
  ('37029', 3, 'Atividades relacionadas a esgoto, exceto a gestão de redes'),
  ('38114', 3, 'Coleta de resíduos não-perigosos'),
  ('38122', 3, 'Coleta de resíduos perigosos'),
  ('38211', 3, 'Tratamento e disposição de resíduos não-perigosos'),
  ('38220', 3, 'Tratamento e disposição de resíduos perigosos'),
  ('38319', 3, 'Recuperação de materiais metálicos'),
  ('38327', 3, 'Recuperação de materiais plásticos'),
  ('38394', 3, 'Recuperação de materiais não especificados anteriormente'),
  ('39005', 3, 'Descontaminação e outros serviços de gestão de resíduos'),
  ('41107', 1, 'Incorporação de empreendimentos imobiliários'),
  ('41204', 3, 'Construção de edifícios'),
  ('42111', 4, 'Construção de rodovias e ferrovias'),
  ('42120', 4, 'Construção de obras-de-arte especiais'),
  ('42138', 3, 'Obras de urbanização - ruas, praças e calçadas'),
  ('42219', 4, 'Obras para geração e distribuição de energia elétrica e para telecomunicações'),
  ('42227', 4, 'Construção de redes de abastecimento de água, coleta de esgoto e construções correlatas'),
  ('42235', 4, 'Construção de redes de transportes por dutos, exceto para água e esgoto'),
  ('42910', 4, 'Obras portuárias, marítimas e fluviais'),
  ('42928', 4, 'Montagem de instalações industriais e de estruturas metálicas'),
  ('42995', 3, 'Obras de engenharia civil não especificadas anteriormente'),
  ('43118', 4, 'Demolição e preparação de canteiros de obras'),
  ('43126', 4, 'Perfurações e sondagens'),
  ('43134', 3, 'Obras de terraplenagem'),
  ('43193', 3, 'Serviços de preparação do terreno não especificados anteriormente'),
  ('43215', 3, 'Instalações elétricas'),
  ('43223', 3, 'Instalações hidráulicas, de sistemas de ventilação e refrigeração'),
  ('43291', 3, 'Obras de instalações em construções não especificadas anteriormente'),
  ('43304', 3, 'Obras de acabamento'),
  ('43916', 4, 'Obras de fundações'),
  ('43991', 3, 'Serviços especializados para construção não especificados anteriormente'),
  ('45111', 2, 'Comércio a varejo e por atacado de veículos automotores'),
  ('45129', 2, 'Representantes comerciais e agentes do comércio de veículos automotores'),
  ('45200', 3, 'Manutenção e reparação de veículos automotores'),
  ('45307', 2, 'Comércio de peças e acessórios para veículos automotores'),
  ('45412', 2, 'Comércio por atacado e a varejo de motocicletas, peças e acessórios'),
  ('45421', 2, 'Representantes comerciais e agentes do comércio de motocicletas, peças e acessórios'),
  ('45439', 3, 'Manutenção e reparação de motocicletas'),
  ('46117', 2, 'Representantes comerciais e agentes do comércio de matérias-primas agrícolas e animais vivos'),
  ('46125', 2, 'Representantes comerciais e agentes do comércio de combustíveis, minerais, produtos siderúrgicos e químicos'),
  ('46133', 2, 'Representantes comerciais e agentes do comércio de madeira, material de construção e ferragens'),
  ('46141', 2, 'Representantes comerciais e agentes do comércio de máquinas, equipamentos, embarcações e aeronaves'),
  ('46150', 2, 'Representantes comerciais e agentes do comércio de eletrodomésticos, móveis e artigos de uso doméstico'),
  ('46168', 2, 'Representantes comerciais e agentes do comércio de têxteis, vestuário, calçados e artigos de viagem'),
  ('46176', 2, 'Representantes comerciais e agentes do comércio de produtos alimentícios, bebidas e fumo'),
  ('46184', 2, 'Representantes comerciais e agentes do comércio especializado em produtos não especificados anteriormente'),
  ('46192', 2, 'Representantes comerciais e agentes do comércio de mercadorias em geral não especializado'),
  ('46214', 2, 'Comércio atacadista de café em grão'),
  ('46222', 2, 'Comércio atacadista de soja'),
  ('46231', 2, 'Comércio atacadista de animais vivos, alimentos para animais e matérias-primas agrícolas, exceto café e soja'),
  ('46311', 2, 'Comércio atacadista de leite e laticínios'),
  ('46320', 2, 'Comércio atacadista de cereais e leguminosas beneficiados, farinhas, amidos e féculas'),
  ('46338', 2, 'Comércio atacadista de hortifrutigranjeiros'),
  ('46346', 2, 'Comércio atacadista de carnes, produtos da carne e pescado'),
  ('46354', 2, 'Comércio atacadista de bebidas'),
  ('46362', 2, 'Comércio atacadista de produtos do fumo'),
  ('46371', 2, 'Comércio atacadista especializado em produtos alimentícios não especificados anteriormente'),
  ('46397', 2, 'Comércio atacadista de produtos alimentícios em geral'),
  ('46419', 2, 'Comércio atacadista de tecidos, artefatos de tecidos e de armarinho'),
  ('46427', 2, 'Comércio atacadista de artigos do vestuário e acessórios'),
  ('46435', 2, 'Comércio atacadista de calçados e artigos de viagem'),
  ('46443', 2, 'Comércio atacadista de produtos farmacêuticos para uso humano e veterinário'),
  ('46451', 2, 'Comércio atacadista de instrumentos e materiais para uso médico, cirúrgico, ortopédico e odontológico'),
  ('46460', 2, 'Comércio atacadista de cosméticos, produtos de perfumaria e de higiene pessoal'),
  ('46478', 2, 'Comércio atacadista de artigos de escritório e de papelaria; livros, jornais e outras publicações'),
  ('46494', 2, 'Comércio atacadista de equipamentos e artigos de uso pessoal e doméstico não especificados anteriormente'),
  ('46516', 3, 'Comércio atacadista de computadores, periféricos e suprimentos de informática'),
  ('46524', 3, 'Comércio atacadista de componentes eletrônicos e equipamentos de telefonia e comunicação'),
  ('46613', 3, 'Comércio atacadista de máquinas, aparelhos e equipamentos para uso agropecuário; partes e peças'),
  ('46621', 3, 'Comércio atacadista de máquinas, equipamentos para terraplenagem, mineração e construção; partes e peças'),
  ('46630', 3, 'Comércio atacadista de máquinas e equipamentos para uso industrial; partes e peças'),
  ('46648', 3, 'Comércio atacadista de máquinas, aparelhos e equipamentos para uso odonto- médico- hospitalar; partes e peças'),
  ('46656', 3, 'Comércio atacadista de máquinas e equipamentos para uso comercial; partes e peças'),
  ('46699', 3, 'Comércio atacadista de máquinas, aparelhos e equipamentos não especificados anteriormente; partes e peças'),
  ('46711', 3, 'Comércio atacadista de madeira e produtos derivados'),
  ('46729', 3, 'Comércio atacadista de ferragens e ferramentas'),
  ('46737', 3, 'Comércio atacadista de material elétrico'),
  ('46745', 3, 'Comércio atacadista de cimento'),
  ('46796', 3, 'Comércio atacadista especializado de materiais de construção não especificados anteriormente e de materiais de construção em geral'),
  ('46818', 3, 'Comércio atacadista de combustíveis sólidos, líquidos e gasosos, exceto gás natural e GLP'),
  ('46826', 3, 'Comércio atacadista de gás liqüefeito de petróleo (GLP)'),
  ('46834', 3, 'Comércio atacadista de defensivos agrícolas, adubos, fertilizantes e corretivos do solo'),
  ('46842', 3, 'Comércio atacadista de produtos químicos e petroquímicos, exceto agroquímicos'),
  ('46851', 3, 'Comércio atacadista de produtos siderúrgicos e metalúrgicos, exceto para construção'),
  ('46869', 3, 'Comércio atacadista de papel e papelão em bruto e de embalagens'),
  ('46877', 3, 'Comércio atacadista de resíduos e sucatas'),
  ('46893', 3, 'Comércio atacadista especializado de outros produtos intermediários não especificados anteriormente'),
  ('46915', 2, 'Comércio atacadista de mercadorias em geral, com predominância de produtos alimentícios'),
  ('46923', 2, 'Comércio atacadista de mercadorias em geral, com predominância de insumos agropecuários'),
  ('46931', 2, 'Comércio atacadista de mercadorias em geral, sem predominância de alimentos ou de insumos agropecuários'),
  ('47113', 2, 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - hipermercados e supermercados'),
  ('47121', 2, 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - minimercados, mercearias e armazéns'),
  ('47130', 2, 'Comércio varejista de mercadorias em geral, sem predominância de produtos alimentícios'),
  ('47211', 2, 'Comércio varejista de produtos de padaria, laticínio, doces, balas e semelhantes'),
  ('47229', 3, 'Comércio varejista de carnes e pescados - açougues e peixarias'),
  ('47237', 2, 'Comércio varejista de bebidas'),
  ('47245', 2, 'Comércio varejista de hortifrutigranjeiros'),
  ('47296', 2, 'Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente; produtos do fumo'),
  ('47318', 3, 'Comércio varejista de combustíveis para veículos automotores'),
  ('47326', 3, 'Comércio varejista de lubrificantes'),
  ('47415', 2, 'Comércio varejista de tintas e materiais para pintura'),
  ('47423', 1, 'Comércio varejista de material elétrico'),
  ('47431', 2, 'Comércio varejista de vidros'),
  ('47440', 2, 'Comércio varejista de ferragens, madeira e materiais de construção'),
  ('47512', 1, 'Comércio varejista especializado de equipamentos e suprimentos de informática'),
  ('47521', 1, 'Comércio varejista especializado de equipamentos de telefonia e comunicação'),
  ('47539', 1, 'Comércio varejista especializado de eletrodomésticos e equipamentos de áudio e vídeo'),
  ('47547', 1, 'Comércio varejista especializado de móveis, colchoaria e artigos de iluminação'),
  ('47555', 1, 'Comércio varejista especializado de tecidos e artigos de cama, mesa e banho'),
  ('47563', 1, 'Comércio varejista especializado de instrumentos musicais e acessórios'),
  ('47571', 1, 'Comércio varejista especializado de peças e acessórios para aparelhos eletroeletrônicos para uso doméstico, exceto informática e comunicação'),
  ('47598', 1, 'Comércio varejista de artigos de uso doméstico não especificados anteriormente'),
  ('47610', 1, 'Comércio varejista de livros, jornais, revistas e papelaria'),
  ('47628', 1, 'Comércio varejista de discos, CDs, DVDs e fitas'),
  ('47636', 1, 'Comércio varejista de artigos recreativos e esportivos'),
  ('47717', 2, 'Comércio varejista de produtos farmacêuticos para uso humano e veterinário'),
  ('47725', 1, 'Comércio varejista de cosméticos, produtos de perfumaria e de higiene pessoal'),
  ('47733', 1, 'Comércio varejista de artigos médicos e ortopédicos'),
  ('47741', 1, 'Comércio varejista de artigos de óptica'),
  ('47814', 1, 'Comércio varejista de artigos do vestuário e acessórios'),
  ('47822', 1, 'Comércio varejista de calçados e artigos de viagem'),
  ('47831', 1, 'Comércio varejista de jóias e relógios'),
  ('47849', 3, 'Comércio varejista de gás liqüefeito de petróleo (GLP)'),
  ('47857', 2, 'Comércio varejista de artigos usados'),
  ('47890', 1, 'Comércio varejista de outros produtos novos não especificados anteriormente'),
  ('47903', 2, 'Comércio ambulante e outros tipos de comércio varejista'),
  ('49116', 3, 'Transporte ferroviário de carga'),
  ('49124', 3, 'Transporte metroferroviário de passageiros'),
  ('49213', 3, 'Transporte rodoviário coletivo de passageiros, com itinerário fixo, municipal e em região metropolitana'),
  ('49221', 3, 'Transporte rodoviário coletivo de passageiros, com itinerário fixo, intermunicipal, interestadual e internacional'),
  ('49230', 3, 'Transporte rodoviário de táxi'),
  ('49248', 3, 'Transporte escolar'),
  ('49299', 3, 'Transporte rodoviário coletivo de passageiros, sob regime de fretamento, e outros transportes rodoviários não especificados anteriormente'),
  ('49302', 3, 'Transporte rodoviário de carga'),
  ('49400', 3, 'Transporte dutoviário'),
  ('49507', 3, 'Trens turísticos, teleféricos e similares'),
  ('50114', 3, 'Transporte marítimo de cabotagem'),
  ('50122', 3, 'Transporte marítimo de longo curso'),
  ('50211', 3, 'Transporte por navegação interior de carga'),
  ('50220', 3, 'Transporte por navegação interior de passageiros em linhas regulares'),
  ('50301', 3, 'Navegação de apoio'),
  ('50912', 3, 'Transporte por navegação de travessia'),
  ('50998', 3, 'Transportes aquaviários não especificados anteriormente'),
  ('51111', 3, 'Transporte aéreo de passageiros regular'),
  ('51129', 3, 'Transporte aéreo de passageiros não-regular'),
  ('51200', 3, 'Transporte aéreo de carga'),
  ('51307', 3, 'Transporte espacial'),
  ('52117', 3, 'Armazenamento'),
  ('52125', 3, 'Carga e descarga'),
  ('52214', 3, 'Concessionárias de rodovias, pontes, túneis e serviços relacionados'),
  ('52222', 3, 'Terminais rodoviários e ferroviários'),
  ('52231', 3, 'Estacionamento de veículos'),
  ('52290', 3, 'Atividades auxiliares dos transportes terrestres não especificadas anteriormente'),
  ('52311', 3, 'Gestão de portos e terminais'),
  ('52320', 3, 'Atividades de agenciamento marítimo'),
  ('52397', 3, 'Atividades auxiliares dos transportes aquaviários não especificadas anteriormente'),
  ('52401', 3, 'Atividades auxiliares dos transportes aéreos'),
  ('52508', 3, 'Atividades relacionadas à organização do transporte de carga'),
  ('53105', 2, 'Atividades de Correio'),
  ('53202', 2, 'Atividades de malote e de entrega'),
  ('55108', 2, 'Hotéis e similares'),
  ('55906', 2, 'Outros tipos de alojamento não especificados anteriormente'),
  ('56112', 2, 'Restaurantes e outros estabelecimentos de serviços de alimentação e bebidas'),
  ('56121', 2, 'Serviços ambulantes de alimentação'),
  ('56201', 2, 'Serviços de catering, bufê e outros serviços de comida preparada'),
  ('58115', 3, 'Edição de livros'),
  ('58123', 3, 'Edição de jornais'),
  ('58131', 3, 'Edição de revistas'),
  ('58191', 3, 'Edição de cadastros, listas e outros produtos gráficos'),
  ('58212', 3, 'Edição integrada à impressão de livros'),
  ('58221', 3, 'Edição integrada à impressão de jornais'),
  ('58239', 3, 'Edição integrada à impressão de revistas'),
  ('58298', 3, 'Edição integrada à impressão de cadastros, listas e outros produtos gráficos'),
  ('59111', 2, 'Atividades de produção cinematográfica, de vídeos e de programas de televisão'),
  ('59120', 2, 'Atividades de pós-produção cinematográfica, de vídeos e de programas de televisão'),
  ('59138', 2, 'Distribuição cinematográfica, de vídeo e de programas de televisão'),
  ('59146', 2, 'Atividades de exibição cinematográfica'),
  ('59201', 2, 'Atividades de gravação de som e de edição de música'),
  ('60101', 2, 'Atividades de rádio'),
  ('60217', 2, 'Atividades de televisão aberta'),
  ('60225', 2, 'Programadoras e atividades relacionadas à televisão por assinatura'),
  ('61108', 2, 'Telecomunicações por fio'),
  ('61205', 2, 'Telecomunicações sem fio'),
  ('61302', 2, 'Telecomunicações por satélite'),
  ('61418', 2, 'Operadoras de televisão por assinatura por cabo'),
  ('61426', 2, 'Operadoras de televisão por assinatura por microondas'),
  ('61434', 2, 'Operadoras de televisão por assinatura por satélite'),
  ('61906', 2, 'Outras atividades de telecomunicações'),
  ('62015', 2, 'Desenvolvimento de programas de computador sob encomenda'),
  ('62023', 2, 'Desenvolvimento e licenciamento de programas de computador customizáveis'),
  ('62031', 2, 'Desenvolvimento e licenciamento de programas de computador não-customizáveis'),
  ('62040', 2, 'Consultoria em tecnologia da informação'),
  ('62091', 2, 'Suporte técnico, manutenção e outros serviços em tecnologia da informação'),
  ('63119', 2, 'Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na internet'),
  ('63194', 2, 'Portais, provedores de conteúdo e outros serviços de informação na internet'),
  ('63917', 2, 'Agências de notícias'),
  ('63992', 2, 'Outras atividades de prestação de serviços de informação não especificadas anteriormente'),
  ('64107', 1, 'Banco Central'),
  ('64212', 1, 'Bancos comerciais'),
  ('64221', 1, 'Bancos múltiplos, com carteira comercial'),
  ('64239', 1, 'Caixas econômicas'),
  ('64247', 1, 'Crédito cooperativo'),
  ('64310', 1, 'Bancos múltiplos, sem carteira comercial'),
  ('64328', 1, 'Bancos de investimento'),
  ('64336', 1, 'Bancos de desenvolvimento'),
  ('64344', 1, 'Agências de fomento'),
  ('64352', 1, 'Crédito imobiliário'),
  ('64361', 1, 'Sociedades de crédito, financiamento e investimento - financeiras'),
  ('64379', 1, 'Sociedades de crédito ao microempreendedor'),
  ('64387', 1, 'Bancos de câmbio e outras instituições de intermediação não-monetária'),
  ('64409', 1, 'Arrendamento mercantil'),
  ('64506', 1, 'Sociedades de capitalização'),
  ('64611', 1, 'Holdings de instituições financeiras'),
  ('64620', 1, 'Holdings de instituições não-financeiras'),
  ('64638', 1, 'Outras sociedades de participação, exceto holdings'),
  ('64701', 1, 'Fundos de investimento'),
  ('64913', 1, 'Sociedades de fomento mercantil - factoring'),
  ('64921', 1, 'Securitização de créditos'),
  ('64930', 1, 'Administração de consórcios para aquisição de bens e direitos'),
  ('64999', 1, 'Outras atividades de serviços financeiros não especificadas anteriormente'),
  ('65111', 1, 'Seguros de vida'),
  ('65120', 1, 'Seguros não-vida'),
  ('65201', 1, 'Seguros-saúde'),
  ('65308', 1, 'Resseguros'),
  ('65413', 1, 'Previdência complementar fechada'),
  ('65421', 1, 'Previdência complementar aberta'),
  ('65502', 1, 'Planos de saúde'),
  ('66118', 1, 'Administração de bolsas e mercados de balcão organizados'),
  ('66126', 1, 'Atividades de intermediários em transações de títulos, valores mobiliários e mercadorias'),
  ('66134', 1, 'Administração de cartões de crédito'),
  ('66193', 1, 'Atividades auxiliares dos serviços financeiros não especificadas anteriormente'),
  ('66215', 1, 'Avaliação de riscos e perdas'),
  ('66223', 1, 'Corretores e agentes de seguros, de planos de previdência complementar e de saúde'),
  ('66291', 1, 'Atividades auxiliares dos seguros, da previdência complementar e dos planos de saúde não especificadas anteriormente'),
  ('66304', 1, 'Atividades de administração de fundos por contrato ou comissão'),
  ('68102', 1, 'Atividades imobiliárias de imóveis próprios'),
  ('68218', 1, 'Intermediação na compra, venda e aluguel de imóveis'),
  ('68226', 1, 'Gestão e administração da propriedade imobiliária'),
  ('69117', 1, 'Atividades jurídicas, exceto cartórios'),
  ('69125', 1, 'Cartórios'),
  ('69206', 1, 'Atividades de contabilidade, consultoria e auditoria contábil e tributária'),
  ('70107', 1, 'Sedes de empresas e unidades administrativas locais'),
  ('70204', 1, 'Atividades de consultoria em gestão empresarial'),
  ('71111', 1, 'Serviços de arquitetura'),
  ('71120', 1, 'Serviços de engenharia'),
  ('71197', 1, 'Atividades técnicas relacionadas à arquitetura e engenharia'),
  ('71201', 2, 'Testes e análises técnicas'),
  ('72100', 2, 'Pesquisa e desenvolvimento experimental em ciências físicas e naturais'),
  ('72207', 2, 'Pesquisa e desenvolvimento experimental em ciências sociais e humanas'),
  ('73114', 1, 'Agências de publicidade'),
  ('73122', 1, 'Agenciamento de espaços para publicidade, exceto em veículos de comunicação'),
  ('73190', 1, 'Atividades de publicidade não especificadas anteriormente'),
  ('73203', 1, 'Pesquisas de mercado e de opinião pública'),
  ('74102', 1, 'Design e decoração de interiores'),
  ('74200', 2, 'Atividades fotográficas e similares'),
  ('74901', 1, 'Atividades profissionais, científicas e técnicas não especificadas anteriormente'),
  ('75001', 3, 'Atividades veterinárias'),
  ('77110', 1, 'Locação de automóveis sem condutor'),
  ('77195', 1, 'Locação de meios de transporte, exceto automóveis, sem condutor'),
  ('77217', 1, 'Aluguel de equipamentos recreativos e esportivos'),
  ('77225', 1, 'Aluguel de fitas de vídeo, DVDs e similares'),
  ('77233', 1, 'Aluguel de objetos do vestuário, jóias e acessórios'),
  ('77292', 1, 'Aluguel de objetos pessoais e domésticos não especificados anteriormente'),
  ('77314', 1, 'Aluguel de máquinas e equipamentos agrícolas sem operador'),
  ('77322', 1, 'Aluguel de máquinas e equipamentos para construção sem operador'),
  ('77331', 1, 'Aluguel de máquinas e equipamentos para escritório'),
  ('77390', 1, 'Aluguel de máquinas e equipamentos não especificados anteriormente'),
  ('77403', 1, 'Gestão de ativos intangíveis não-financeiros'),
  ('78108', 1, 'Seleção e agenciamento de mão-de-obra'),
  ('78205', 1, 'Locação de mão-de-obra temporária'),
  ('78302', 1, 'Fornecimento e gestão de recursos humanos para terceiros'),
  ('79112', 1, 'Agências de viagens'),
  ('79121', 1, 'Operadores turísticos'),
  ('79902', 1, 'Serviços de reservas e outros serviços de turismo não especificados anteriormente'),
  ('80111', 3, 'Atividades de vigilância e segurança privada'),
  ('80129', 3, 'Atividades de transporte de valores'),
  ('80200', 3, 'Atividades de monitoramento de sistemas de segurança'),
  ('80307', 3, 'Atividades de investigação particular'),
  ('81117', 2, 'Serviços combinados para apoio a edifícios, exceto condomínios prediais'),
  ('81125', 2, 'Condomínios prediais'),
  ('81214', 3, 'Limpeza em prédios e em domicílios'),
  ('81222', 3, 'Imunização e controle de pragas urbanas'),
  ('81290', 3, 'Atividades de limpeza não especificadas anteriormente'),
  ('81303', 1, 'Atividades paisagísticas'),
  ('82113', 1, 'Serviços combinados de escritório e apoio administrativo'),
  ('82199', 2, 'Fotocópias, preparação de documentos e outros serviços especializados de apoio administrativo'),
  ('82202', 2, 'Atividades de teleatendimento'),
  ('82300', 2, 'Atividades de organização de eventos, exceto culturais e esportivos'),
  ('82911', 2, 'Atividades de cobrança e informações cadastrais'),
  ('82920', 2, 'Envasamento e empacotamento sob contrato'),
  ('82997', 2, 'Atividades de serviços prestados principalmente às empresas não especificadas anteriormente'),
  ('84116', 1, 'Administração pública em geral'),
  ('84124', 1, 'Regulação das atividades de saúde, educação, serviços culturais e outros serviços sociais'),
  ('84132', 1, 'Regulação das atividades econômicas'),
  ('84213', 1, 'Relações exteriores'),
  ('84221', 1, 'Defesa'),
  ('84230', 1, 'Justiça'),
  ('84248', 1, 'Segurança e ordem pública'),
  ('84256', 1, 'Defesa Civil'),
  ('84302', 1, 'Seguridade social obrigatória'),
  ('85112', 2, 'Educação infantil - creche'),
  ('85121', 2, 'Educação infantil - pré-escola'),
  ('85139', 2, 'Ensino fundamental'),
  ('85201', 2, 'Ensino médio'),
  ('85317', 2, 'Educação superior - graduação'),
  ('85325', 2, 'Educação superior - graduação e pós-graduação'),
  ('85333', 2, 'Educação superior - pós-graduação e extensão'),
  ('85414', 2, 'Educação profissional de nível técnico'),
  ('85422', 2, 'Educação profissional de nível tecnológico'),
  ('85503', 2, 'Atividades de apoio à educação'),
  ('85911', 2, 'Ensino de esportes'),
  ('85929', 2, 'Ensino de arte e cultura'),
  ('85937', 2, 'Ensino de idiomas'),
  ('85996', 2, 'Atividades de ensino não especificadas anteriormente'),
  ('86101', 3, 'Atividades de atendimento hospitalar'),
  ('86216', 3, 'Serviços móveis de atendimento a urgências'),
  ('86224', 3, 'Serviços de remoção de pacientes, exceto os serviços móveis de atendimento a urgências'),
  ('86305', 3, 'Atividades de atenção ambulatorial executadas por médicos e odontólogos'),
  ('86402', 3, 'Atividades de serviços de complementação diagnóstica e terapêutica'),
  ('86500', 2, 'Atividades de profissionais da área de saúde, exceto médicos e odontólogos'),
  ('86607', 1, 'Atividades de apoio à gestão de saúde'),
  ('86909', 1, 'Atividades de atenção à saúde humana não especificadas anteriormente'),
  ('87115', 1, 'Atividades de assistência a idosos, deficientes físicos, imunodeprimidos e convalescentes prestadas em residências coletivas e particulares'),
  ('87123', 1, 'Atividades de fornecimento de infra-estrutura de apoio e assistência a paciente no domicílio'),
  ('87204', 1, 'Atividades de assistência psicossocial e à saúde a portadores de distúrbios psíquicos, deficiência mental e dependência química'),
  ('87301', 1, 'Atividades de assistência social prestadas em residências coletivas e particulares'),
  ('88006', 1, 'Serviços de assistência social sem alojamento'),
  ('90019', 2, 'Artes cênicas, espetáculos e atividades complementares'),
  ('90027', 2, 'Criação artística'),
  ('90035', 1, 'Gestão de espaços para artes cênicas, espetáculos e outras atividades artísticas'),
  ('91015', 2, 'Atividades de bibliotecas e arquivos'),
  ('91023', 2, 'Atividades de museus e de exploração, restauração artística e conservação de lugares e prédios históricos e atrações similares'),
  ('91031', 2, 'Atividades de jardins botânicos, zoológicos, parques nacionais, reservas ecológicas e áreas de proteção ambiental'),
  ('92003', 1, 'Atividades de exploração de jogos de azar e apostas'),
  ('93115', 1, 'Gestão de instalações de esportes'),
  ('93123', 2, 'Clubes sociais, esportivos e similares'),
  ('93131', 2, 'Atividades de condicionamento físico'),
  ('93191', 2, 'Atividades esportivas não especificadas anteriormente'),
  ('93212', 2, 'Parques de diversão e parques temáticos'),
  ('93298', 2, 'Atividades de recreação e lazer não especificadas anteriormente'),
  ('94111', 1, 'Atividades de organizações associativas patronais e empresariais'),
  ('94120', 1, 'Atividades de organizações associativas profissionais'),
  ('94201', 1, 'Atividades de organizações sindicais'),
  ('94308', 1, 'Atividades de associações de defesa de direitos sociais'),
  ('94910', 1, 'Atividades de organizações religiosas'),
  ('94928', 1, 'Atividades de organizações políticas'),
  ('94936', 1, 'Atividades de organizações associativas ligadas à cultura e à arte'),
  ('94995', 1, 'Atividades associativas não especificadas anteriormente'),
  ('95118', 3, 'Reparação e manutenção de computadores e de equipamentos periféricos'),
  ('95126', 3, 'Reparação e manutenção de equipamentos de comunicação'),
  ('95215', 3, 'Reparação e manutenção de equipamentos eletroeletrônicos de uso pessoal e doméstico'),
  ('95291', 3, 'Reparação e manutenção de objetos e equipamentos pessoais e domésticos não especificados anteriormente'),
  ('96017', 2, 'Lavanderias, tinturarias e toalheiros'),
  ('96025', 2, 'Cabeleireiros e outras atividades de tratamento de beleza'),
  ('96033', 2, 'Atividades funerárias e serviços relacionados'),
  ('96092', 2, 'Atividades de serviços pessoais não especificadas anteriormente'),
  ('97005', 2, 'Serviços domésticos'),
  ('99008', 1, 'Organismos internacionais e outras instituições extraterritoriais')
ON CONFLICT (cnae_classe) DO UPDATE
  SET grau_risco  = EXCLUDED.grau_risco,
      denominacao = EXCLUDED.denominacao;

-- Trava: a carga tem que ter as 673 classes da CNAE 2.0.
DO $$
DECLARE n INT;
BEGIN
  SELECT count(*) INTO n FROM public.cnae_grau_risco;
  IF n <> 673 THEN
    RAISE EXCEPTION 'v141: esperava 673 classes na tabela, encontrei %', n;
  END IF;
END $$;

-- Procedencia do grau em cada empresa -----------------------------------------
-- NULL nos cadastros antigos: nao da para saber como foram preenchidos, e
-- inventar procedencia seria pior que admitir que nao se sabe.
ALTER TABLE public.empresas
  ADD COLUMN IF NOT EXISTS grau_risco_origem TEXT,
  ADD COLUMN IF NOT EXISTS grau_risco_norma  INT;

COMMENT ON COLUMN public.empresas.grau_risco_origem
  IS 'NORMA = veio do Anexo I da NR-4 pelo CNAE; MANUAL = pessoa escolheu outro valor. NULL = cadastro anterior a v141.';
COMMENT ON COLUMN public.empresas.grau_risco_norma
  IS 'O que a NR-4 indicava no momento da gravacao. Permite auditar divergencia mesmo se a norma mudar depois.';

DO $$
BEGIN
  ALTER TABLE public.empresas
    ADD CONSTRAINT empresas_grau_origem_chk
    CHECK (grau_risco_origem IS NULL OR grau_risco_origem IN ('NORMA', 'MANUAL'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Funcao de consulta: recebe o CNAE em qualquer formato (subclasse com ou
-- sem mascara, classe com ou sem mascara) e devolve o grau da norma.
CREATE OR REPLACE FUNCTION public.grau_risco_por_cnae(p_cnae TEXT)
RETURNS INT
LANGUAGE sql STABLE AS $$
  SELECT g.grau_risco
    FROM public.cnae_grau_risco g
   WHERE g.cnae_classe = substr(regexp_replace(coalesce(p_cnae, ''), '[^0-9]', '', 'g'), 1, 5)
$$;

COMMENT ON FUNCTION public.grau_risco_por_cnae(TEXT)
  IS 'Grau de risco da NR-4 para um CNAE (subclasse ou classe, com ou sem mascara). NULL se o CNAE nao existir no Anexo I.';

-- RLS: leitura para qualquer usuario autenticado; ninguem escreve pela app.
-- A tabela so muda por migration, quando a norma mudar.
ALTER TABLE public.cnae_grau_risco ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "auth read cnae_grau_risco" ON public.cnae_grau_risco;
CREATE POLICY "auth read cnae_grau_risco"
  ON public.cnae_grau_risco FOR SELECT TO authenticated USING (true);

COMMIT;
