-- v249 — Dimensionamento (DIM-01): o schema do Chabra Dimensiona dentro do painel_sst.
--
-- Numerada v249 em 2026-09-22 depois de a v243 ser tomada por outra frente enquanto
-- esta era escrita (v243–v248 entraram no mesmo dia). O número sai do banco, no ato.
--
-- ADITIVA. Nada é removido aqui: as 7 tabelas `prod_*` do módulo Produtividade e as
-- permissões atuais continuam intactas até a v244, que só entra depois que a migração
-- de dados e o front estiverem provados. Rollback: scripts/sql/v249_rollback_dimensionamento.sql.
--
-- Origem: joaojefferson-hash/Dimensionamento_Chabra @ e5671c2, schema real extraído por
-- `pg_dump --schema-only` do Supabase do João em 2026-09-22 (12 tabelas, 11 funções, zero
-- tipos custom). As tabelas entram com prefixo `dim_` porque `unidades`, `colaboradores` e
-- `funcoes` JÁ EXISTEM no painel_sst com outro significado.
--
-- Três decisões que se afastam da origem, de propósito:
--   1. Identidade: a origem usa `papel_atual()`/`pode_editar()` lendo `app_metadata.papel`
--      (Supabase). Aqui quem decide é `public.caller_eh_admin()` (v242, memoizado por
--      transação) — o módulo é admin-only por decisão do operador (D7).
--   2. `GENERATED BY DEFAULT AS IDENTITY` no lugar de `ALWAYS`: a carga de dados da Fase 1.2
--      precisa preservar os ids do histórico sem `OVERRIDING SYSTEM VALUE` em cada insert.
--   3. `importar_backup` NÃO é portada. Era o caminho da origem para mover dados entre
--      instalações; aqui o backup é o do painel (dump diário + weekly cifrado). Uma RPC que
--      substitui TODOS os dados numa transação é superfície grande demais para o ganho.
--
-- As tabelas nascem SEM privilégio e ganham o grant explicitamente — não dependemos de
-- qual `ALTER DEFAULT PRIVILEGES` está valendo nesta base.

-- NO JCN: guarda de dono adaptada (as funcoes SECURITY DEFINER aqui pertencem
-- a 'postgres'; no self-host, a 'chabra_admin') e sem o insert em
-- public.schema_migrations, que e o rastreador do painel self-host.
-- dim_portes e dim_parametros nascem VAZIAS: os dados do painel vieram do
-- scripts/dim01-carga.sh, que carrega o cadastro da consultoria da Chabra e
-- nao atravessa para ca. Ver a nota da v253 sobre o modulo ficar dormente.

begin;

do $$ begin
  if current_user <> 'postgres' then
    raise exception 'aplicar como postgres (dono das funções SECURITY DEFINER)';
  end if;
  if to_regprocedure('public.caller_eh_admin()') is null then
    raise exception 'v242 (caller_eh_admin) é pré-requisito desta migration';
  end if;
end $$;

-- ─── 1) Cadastros ────────────────────────────────────────────────────────────

create table if not exists public.dim_unidades (
  id          uuid primary key default gen_random_uuid(),
  nome        text not null constraint dim_unidades_nome_check check (btrim(nome) <> ''),
  codigo_api  text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create unique index if not exists dim_unidades_nome_key on public.dim_unidades (lower(btrim(nome)));
create unique index if not exists dim_unidades_codigo_api_idx on public.dim_unidades (codigo_api) where codigo_api is not null;
comment on table public.dim_unidades is 'DIM-01: filiais do dimensionamento. NÃO é public.unidades (as unidades do painel SST).';

create table if not exists public.dim_funcoes (
  id             uuid primary key default gen_random_uuid(),
  nome           text not null constraint dim_funcoes_nome_check check (btrim(nome) <> ''),
  tipo_producao  text not null default 'nenhuma'
                 constraint dim_funcoes_tipo_producao_check check (tipo_producao in ('tecnico','administrativo','nenhuma')),
  ordem          integer not null default 0,
  chefia         boolean not null default false,
  coordena       text not null default 'todos'
                 constraint dim_funcoes_coordena_check check (coordena in ('todos','tecnicos','administrativos')),
  responde_para  uuid references public.dim_funcoes(id) on delete set null,
  custo_mensal   numeric(12,2) not null default 0
                 constraint dim_funcoes_custo_mensal_check check (custo_mensal >= 0),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint dim_funcoes_responde_para_diferente check (responde_para is null or responde_para <> id)
);
create unique index if not exists dim_funcoes_nome_key on public.dim_funcoes (lower(btrim(nome)));
create index if not exists dim_funcoes_responde_para_idx on public.dim_funcoes (responde_para);

create table if not exists public.dim_colaboradores (
  id                 uuid primary key default gen_random_uuid(),
  nome               text not null constraint dim_colaboradores_nome_check check (btrim(nome) <> ''),
  funcao_id          uuid not null references public.dim_funcoes(id) on delete restrict,
  empresas_dia       numeric(6,2) not null default 2 constraint dim_colaboradores_empresas_dia_check check (empresas_dia >= 0),
  inspecoes_dia      numeric(6,2) not null default 2 constraint dim_colaboradores_inspecoes_dia_check check (inspecoes_dia >= 0),
  relatorios_dia     numeric(6,2) not null default 2 constraint dim_colaboradores_relatorios_dia_check check (relatorios_dia >= 0),
  data_admissao      date,
  data_desligamento  date,
  custo_mensal       numeric(12,2) constraint dim_colaboradores_custo_mensal_check check (custo_mensal >= 0),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  constraint dim_colaboradores_datas check (
    data_desligamento is null or data_admissao is null or data_desligamento >= data_admissao)
);
create index if not exists dim_colaboradores_funcao_id_idx on public.dim_colaboradores (funcao_id);

create table if not exists public.dim_colaborador_unidades (
  colaborador_id  uuid not null references public.dim_colaboradores(id) on delete cascade,
  unidade_id      uuid not null references public.dim_unidades(id) on delete cascade,
  percentual      numeric(5,2) not null
                  constraint dim_colaborador_unidades_percentual_check check (percentual > 0 and percentual <= 100),
  created_at      timestamptz not null default now(),
  primary key (colaborador_id, unidade_id)
);
create index if not exists dim_colaborador_unidades_unidade_idx on public.dim_colaborador_unidades (unidade_id);

create table if not exists public.dim_portes (
  codigo  text primary key constraint dim_portes_codigo_check check (btrim(codigo) <> ''),
  nome    text not null constraint dim_portes_nome_check check (btrim(nome) <> ''),
  peso    numeric(4,2) not null constraint dim_portes_peso_check check (peso > 0),
  ordem   smallint not null default 0
);

create table if not exists public.dim_clientes_porte (
  codigo      text primary key constraint dim_clientes_porte_codigo_check check (btrim(codigo) <> ''),
  nome        text not null default '',
  porte       text not null references public.dim_portes(codigo),
  cnpj        text,
  condicao    text constraint dim_clientes_porte_condicao_check check (
                condicao is null or condicao in ('mensal','exclusiva_tst','sem_avaliacao','contrato_novo')),
  updated_at  timestamptz not null default now()
);
create index if not exists dim_clientes_porte_cnpj_idx on public.dim_clientes_porte (cnpj) where cnpj is not null;

create table if not exists public.dim_documentos (
  id                   uuid primary key default gen_random_uuid(),
  nome                 text not null constraint dim_documentos_nome_check check (btrim(nome) <> ''),
  horas                numeric(8,2) not null default 0 constraint dim_documentos_horas_check check (horas >= 0),
  periodicidade_meses  integer not null default 0 constraint dim_documentos_periodicidade_check check (periodicidade_meses >= 0),
  responsavel          text not null default 'Técnico de Segurança do Trabalho'
                       constraint dim_documentos_responsavel_check check (
                         responsavel in ('Técnico de Segurança do Trabalho','Administrativo')),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create unique index if not exists dim_documentos_nome_key on public.dim_documentos (lower(btrim(nome)));
comment on table public.dim_documentos is
  'DIM-01/D5: catálogo herdado da origem, onde já estava oculto na UI e fora do cálculo. Dados vieram junto; não há tela.';

create table if not exists public.dim_parametros (
  id             smallint primary key default 1 constraint dim_parametros_id_check check (id = 1),
  dias_uteis     integer[] not null default '{21,18,22,20,20,21,23,21,21,21,19,22}'
                 constraint dim_parametros_dias_uteis_check check (
                   array_length(dias_uteis,1) = 12 and 0 <= all(dias_uteis) and 31 >= all(dias_uteis)),
  ocupacao_alvo  numeric(5,2) not null default 85
                 constraint dim_parametros_ocupacao_check check (ocupacao_alvo > 0 and ocupacao_alvo <= 100),
  prazo_dias     integer not null default 60
                 constraint dim_parametros_prazo_check check (prazo_dias >= 1 and prazo_dias <= 365),
  rampup         integer[] not null default '{50,80}'
                 constraint dim_parametros_rampup_check check (
                   array_length(rampup,1) is null or (array_length(rampup,1) <= 12 and 0 <= all(rampup) and 100 >= all(rampup))),
  updated_at     timestamptz not null default now()
);

-- ─── 2) Movimento ────────────────────────────────────────────────────────────

create table if not exists public.dim_demanda_mensal (
  unidade_id  uuid not null references public.dim_unidades(id) on delete cascade,
  ano         smallint not null constraint dim_demanda_ano_check check (ano >= 2000 and ano <= 2100),
  mes         smallint not null constraint dim_demanda_mes_check check (mes >= 1 and mes <= 12),
  condicao    text not null constraint dim_demanda_condicao_check check (
                condicao in ('mensal','exclusiva_tst','sem_avaliacao','contrato_novo')),
  porte       text not null references public.dim_portes(codigo),
  quantidade  integer not null default 0 constraint dim_demanda_quantidade_check check (quantidade >= 0),
  updated_at  timestamptz not null default now(),
  primary key (unidade_id, ano, mes, condicao, porte)
);
create index if not exists dim_demanda_mensal_ano_mes on public.dim_demanda_mensal (ano, mes);

create table if not exists public.dim_unidade_mes (
  unidade_id       uuid not null references public.dim_unidades(id) on delete cascade,
  ano              smallint not null constraint dim_unidade_mes_ano_check check (ano >= 2000 and ano <= 2100),
  mes              smallint not null constraint dim_unidade_mes_mes_check check (mes >= 1 and mes <= 12),
  clientes_ativos  integer not null default 0 constraint dim_unidade_mes_clientes_check check (clientes_ativos >= 0),
  atendidas        integer not null default 0 constraint dim_unidade_mes_atendidas_check check (atendidas >= 0),
  atendidas_porte  jsonb not null default '{}'::jsonb,
  updated_at       timestamptz not null default now(),
  primary key (unidade_id, ano, mes)
);

create table if not exists public.dim_sincronizacao_sst (
  id                   bigint generated by default as identity primary key,
  executado_em         timestamptz not null default now(),
  ano                  integer not null,
  unidade_id           uuid references public.dim_unidades(id) on delete set null,
  codigo_api           text,
  cobertura            text,
  ultima_varredura_em  timestamptz,
  documentos           integer not null default 0,
  demanda_gravada      integer not null default 0,
  atendidas_gravadas   integer not null default 0,
  aplicada             boolean not null default false,
  mensagem             text
);

create table if not exists public.dim_historico (
  id             bigint generated by default as identity primary key,
  quando         timestamptz not null default now(),
  usuario_id     uuid,
  usuario_email  text,
  usuario_nome   text,
  tabela         text not null,
  operacao       text not null constraint dim_historico_operacao_check check (
                   operacao in ('insert','update','delete','importacao')),
  registro_id    text,
  antes          jsonb,
  depois         jsonb
);
create index if not exists dim_historico_quando_idx on public.dim_historico (quando desc);
comment on column public.dim_historico.usuario_email is
  'DIM-01: identidade de quem mudou. A origem também gravava o e-mail, então o histórico importado chega com autor legível. Daqui em diante vem do JWT — o mesmo caminho de toda a base do painel.';
comment on column public.dim_historico.usuario_id is
  'DIM-01: HERANÇA. É o uuid do auth.users do SUPABASE DO JOÃO, sem correspondente no painel — existe só para não perder a procedência das linhas importadas. Linha nova nasce com NULL aqui; quem identifica é o e-mail.';

-- ─── 3) Funções de apoio (o painel não tem `set_updated_at` genérico) ────────

create or replace function public.dim_set_updated_at() returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end $$;

create or replace function public.dim_checar_soma_alocacoes() returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare total numeric;
begin
  select coalesce(sum(percentual), 0) into total
    from public.dim_colaborador_unidades where colaborador_id = new.colaborador_id;
  if total > 100.0001 then
    raise exception 'A soma das alocações do colaborador não pode passar de 100%% (atual: %)', total || '%'
      using errcode = '23514';
  end if;
  return new;
end $$;

-- Histórico: grava QUEM mudou o quê. Só o gatilho escreve (a tabela é ingravável pelo app).
-- `app.dim_historico = 'off'` desliga durante a carga de dados da Fase 1.2, para não gerar
-- um evento por linha importada.
create or replace function public.dim_registrar_historico() returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  antes   jsonb;
  depois  jsonb;
  rid     text;
  v_email text;
  v_nome  text;
begin
  if coalesce(current_setting('app.dim_historico', true), '') = 'off' then
    return coalesce(new, old);
  end if;

  if tg_op in ('UPDATE','DELETE') then antes  := to_jsonb(old); end if;
  if tg_op in ('INSERT','UPDATE') then depois := to_jsonb(new); end if;
  if tg_op = 'UPDATE' and (antes - 'updated_at') = (depois - 'updated_at') then
    return new;
  end if;

  if tg_table_name in ('dim_colaborador_unidades','dim_demanda_mensal','dim_unidade_mes') then
    if antes is not null then
      antes := antes || jsonb_build_object('unidade_nome',
        (select x.nome from public.dim_unidades x where x.id = (antes->>'unidade_id')::uuid));
    end if;
    if depois is not null then
      depois := depois || jsonb_build_object('unidade_nome',
        (select x.nome from public.dim_unidades x where x.id = (depois->>'unidade_id')::uuid));
    end if;
  end if;
  if tg_table_name = 'dim_colaborador_unidades' then
    if antes is not null then
      antes := antes || jsonb_build_object('colaborador_nome',
        (select x.nome from public.dim_colaboradores x where x.id = (antes->>'colaborador_id')::uuid));
    end if;
    if depois is not null then
      depois := depois || jsonb_build_object('colaborador_nome',
        (select x.nome from public.dim_colaboradores x where x.id = (depois->>'colaborador_id')::uuid));
    end if;
  end if;

  v_email := lower(nullif(auth.jwt() ->> 'email', ''));
  select u.nome into v_nome from public.usuarios u where lower(u.email) = v_email limit 1;

  rid := coalesce(depois->>'id', antes->>'id', depois->>'codigo', antes->>'codigo',
                  concat_ws('/', coalesce(depois, antes)->>'unidade_id',
                                 coalesce(depois, antes)->>'colaborador_id',
                                 coalesce(depois, antes)->>'ano',
                                 coalesce(depois, antes)->>'mes',
                                 coalesce(depois, antes)->>'condicao',
                                 coalesce(depois, antes)->>'porte'));

  insert into public.dim_historico (usuario_email, usuario_nome, tabela, operacao, registro_id, antes, depois)
  values (v_email, v_nome, tg_table_name, lower(tg_op), rid, antes, depois);

  return coalesce(new, old);
end $$;

-- ─── 4) Gatilhos ─────────────────────────────────────────────────────────────

do $$
declare
  t text;
  com_updated text[] := array['dim_unidades','dim_funcoes','dim_colaboradores','dim_documentos','dim_parametros'];
  com_historico text[] := array['dim_unidades','dim_funcoes','dim_colaboradores','dim_colaborador_unidades',
                                'dim_portes','dim_clientes_porte','dim_documentos','dim_demanda_mensal','dim_unidade_mes'];
begin
  foreach t in array com_updated loop
    execute format('drop trigger if exists %I on public.%I', t || '_set_updated_at', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.dim_set_updated_at()',
                   t || '_set_updated_at', t);
  end loop;

  foreach t in array com_historico loop
    execute format('drop trigger if exists %I on public.%I', t || '_historico', t);
    execute format('create trigger %I after insert or update or delete on public.%I for each row execute function public.dim_registrar_historico()',
                   t || '_historico', t);
  end loop;

  -- parâmetros: linha única, só UPDATE interessa
  drop trigger if exists dim_parametros_historico on public.dim_parametros;
  create trigger dim_parametros_historico after update on public.dim_parametros
    for each row execute function public.dim_registrar_historico();

  drop trigger if exists dim_colaborador_unidades_soma on public.dim_colaborador_unidades;
  create trigger dim_colaborador_unidades_soma after insert or update on public.dim_colaborador_unidades
    for each row execute function public.dim_checar_soma_alocacoes();
end $$;

-- ─── 5) Privilégio e RLS — admin-only, fechado por padrão ────────────────────
-- Não dependemos do ALTER DEFAULT PRIVILEGES desta base: revogamos tudo e concedemos
-- explicitamente. `anon` nunca recebe nada. A RLS (caller_eh_admin) é quem barra de fato —
-- a trava por módulo (rls_modulo_tabelas) está em modo `log` e NÃO barra ninguém hoje.

do $$
declare
  t text;
  tabelas text[] := array['dim_unidades','dim_funcoes','dim_colaboradores','dim_colaborador_unidades',
                          'dim_portes','dim_clientes_porte','dim_documentos','dim_parametros',
                          'dim_demanda_mensal','dim_unidade_mes','dim_sincronizacao_sst','dim_historico'];
begin
  foreach t in array tabelas loop
    execute format('revoke all on public.%I from public, anon, authenticated', t);
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists dim_admin on public.%I', t);
  end loop;

  -- 11 tabelas: Admin faz tudo
  foreach t in array tabelas loop
    continue when t = 'dim_historico';
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
    execute format('create policy dim_admin on public.%I for all to authenticated '
                   'using (coalesce(public.caller_eh_admin(), false)) '
                   'with check (coalesce(public.caller_eh_admin(), false))', t);
  end loop;

  -- histórico: leitura para Admin; escrita SÓ pelo gatilho (security definer)
  grant select on public.dim_historico to authenticated;
  create policy dim_admin on public.dim_historico for select to authenticated
    using (coalesce(public.caller_eh_admin(), false));
end $$;

-- ─── 6) Trava por módulo (v236/v240) — aditiva, em modo log não barra ────────
insert into public.rls_modulo_tabelas (tabela, modulo)
select t, 'dimensionamento'
  from unnest(array['dim_unidades','dim_funcoes','dim_colaboradores','dim_colaborador_unidades',
                    'dim_portes','dim_clientes_porte','dim_documentos','dim_parametros',
                    'dim_demanda_mensal','dim_unidade_mes','dim_sincronizacao_sst','dim_historico']) t
 where not exists (select 1 from public.rls_modulo_tabelas x where x.tabela = t);

-- ─── 7) RPCs de escrita ──────────────────────────────────────────────────────
-- Portadas da origem com três mudanças:
--   • A guarda era `auth.uid() is null` + `pode_editar()` (papel do app_metadata). Aqui é
--     `coalesce(public.caller_eh_admin(), false)` — e SEM `coalesce` uma guarda contra NULL
--     não dispara, lição que já custou um furo nesta base (SEC-GESTAO-05).
--   • São SECURITY INVOKER, não DEFINER: a RLS acima já barra o não-Admin, então não há
--     motivo para criar superfície que contorna política. A guarda fica como segunda
--     tranca, para o caso de alguém afrouxar a policy no futuro.
--   • `aplicar_sincronizacao_sst` na origem LIBERAVA quando `auth.uid()` era nulo (o caminho
--     do agendamento). Aqui exige Admin sempre: a rota `/api/dimensionamento/sincronizar`
--     chama com a sessão do próprio usuário, nunca com service_role.

create or replace function public.dim_definir_alocacoes(p_colaborador uuid, p_alocacoes jsonb)
returns void
language plpgsql
set search_path = public
as $_$
begin
  if not coalesce(public.caller_eh_admin(), false) then
    raise exception 'Só administradores alteram o dimensionamento.' using errcode = '42501';
  end if;
  if not exists (select 1 from public.dim_colaboradores where id = p_colaborador) then
    raise exception 'Colaborador não encontrado' using errcode = 'P0002';
  end if;

  delete from public.dim_colaborador_unidades where colaborador_id = p_colaborador;

  insert into public.dim_colaborador_unidades (colaborador_id, unidade_id, percentual)
  select p_colaborador,
         (e.elem->>'unidadeId')::uuid,
         least(100, round((e.elem->>'percentual')::numeric, 2))
  from jsonb_array_elements(coalesce(p_alocacoes, '[]'::jsonb)) as e(elem)
  where (e.elem->>'unidadeId') ~ '^[0-9a-f-]{36}$'
    and coalesce((e.elem->>'percentual')::numeric, 0) > 0
    and exists (select 1 from public.dim_unidades u where u.id = (e.elem->>'unidadeId')::uuid);
end;
$_$;

create or replace function public.dim_substituir_demanda_ano(p_ano integer, p_linhas jsonb, p_condicao text default null)
returns jsonb
language plpgsql
set search_path = public
as $_$
declare
  apagadas integer;
  inseridas integer;
  cond text;
begin
  if not coalesce(public.caller_eh_admin(), false) then
    raise exception 'Só administradores alteram o dimensionamento.' using errcode = '42501';
  end if;
  if p_ano is null or p_ano < 2000 or p_ano > 2100 or p_linhas is null or jsonb_typeof(p_linhas) <> 'array' then
    raise exception 'Dados inválidos' using errcode = '22023';
  end if;
  cond := nullif(trim(coalesce(p_condicao, '')), '');
  if cond is not null and cond not in ('mensal', 'exclusiva_tst', 'sem_avaliacao', 'contrato_novo') then
    raise exception 'Condição inválida' using errcode = '22023';
  end if;

  with ids as (
    select distinct (e->>'unidade_id')::uuid as unidade_id
      from jsonb_array_elements(p_linhas) e
     where (e->>'unidade_id') ~ '^[0-9a-f-]{36}$')
  delete from public.dim_demanda_mensal d using ids
   where d.unidade_id = ids.unidade_id and d.ano = p_ano
     and (cond is null or d.condicao = cond);
  get diagnostics apagadas = row_count;

  insert into public.dim_demanda_mensal (unidade_id, ano, mes, condicao, porte, quantidade)
  select (e->>'unidade_id')::uuid, p_ano, (e->>'mes')::int,
         coalesce(cond, case when e->>'condicao' in ('exclusiva_tst', 'sem_avaliacao', 'contrato_novo')
                             then e->>'condicao' else 'mensal' end),
         case when exists (select 1 from public.dim_portes p where p.codigo = e->>'porte') then e->>'porte' else 'P' end,
         greatest(0, round(coalesce(nullif(e->>'quantidade', '')::numeric, 0)))::int
  from jsonb_array_elements(p_linhas) e
  where (e->>'unidade_id') ~ '^[0-9a-f-]{36}$'
    and (e->>'mes') ~ '^\d{1,2}$' and (e->>'mes')::int between 1 and 12
    and greatest(0, round(coalesce(nullif(e->>'quantidade', '')::numeric, 0)))::int > 0
    and exists (select 1 from public.dim_unidades u where u.id = (e->>'unidade_id')::uuid)
  on conflict (unidade_id, ano, mes, condicao, porte) do update set quantidade = excluded.quantidade;
  get diagnostics inseridas = row_count;

  return jsonb_build_object('apagadas', apagadas, 'inseridas', inseridas, 'condicao', cond);
end;
$_$;

create or replace function public.dim_aplicar_sincronizacao_sst(p_payload jsonb)
returns jsonb
language plpgsql
set search_path = public
as $_$
declare
  ano int := coalesce(nullif(p_payload->>'ano', '')::int, extract(year from now())::int);
  u jsonb;
  uid uuid;
  aplicar boolean;
  apagadas int := 0;
  inseridas int := 0;
  meses int := 0;
  total_demanda int;
  total_atendidas int;
begin
  if not coalesce(public.caller_eh_admin(), false) then
    raise exception 'Só administradores aplicam a sincronização.' using errcode = '42501';
  end if;
  if p_payload is null or jsonb_typeof(p_payload->'unidades') <> 'array' then
    raise exception 'Lote inválido' using errcode = '22023';
  end if;
  if ano < 2000 or ano > 2100 then
    raise exception 'Ano inválido' using errcode = '22023';
  end if;

  for u in select * from jsonb_array_elements(p_payload->'unidades') loop
    uid := nullif(u->>'unidade_id', '')::uuid;
    aplicar := coalesce((u->>'aplicar')::boolean, false);
    total_demanda := 0; total_atendidas := 0;

    if aplicar and uid is not null then
      delete from public.dim_demanda_mensal d where d.unidade_id = uid and d.ano = ano;
      get diagnostics apagadas = row_count;

      insert into public.dim_demanda_mensal (unidade_id, ano, mes, condicao, porte, quantidade)
      select uid, ano, (d->>'mes')::int,
             case when d->>'condicao' in ('exclusiva_tst', 'sem_avaliacao', 'contrato_novo')
                  then d->>'condicao' else 'mensal' end,
             case when exists (select 1 from public.dim_portes pt where pt.codigo = d->>'porte')
                  then d->>'porte' else 'P' end,
             greatest(0, round(coalesce(nullif(d->>'quantidade', '')::numeric, 0)))::int
      from jsonb_array_elements(case when jsonb_typeof(u->'demanda') = 'array' then u->'demanda' else '[]'::jsonb end) as d
      where (d->>'mes') ~ '^\d{1,2}$' and (d->>'mes')::int between 1 and 12
        and greatest(0, round(coalesce(nullif(d->>'quantidade', '')::numeric, 0)))::int > 0
      on conflict (unidade_id, ano, mes, condicao, porte) do update set quantidade = excluded.quantidade;
      get diagnostics inseridas = row_count;
      total_demanda := inseridas;

      for meses in select generate_series(1, 12) loop
        if (u->'atendidas') ? meses::text then
          insert into public.dim_unidade_mes (unidade_id, ano, mes, clientes_ativos, atendidas, atendidas_porte)
          select uid, ano, meses,
                 coalesce((select clientes_ativos from public.dim_unidade_mes m
                            where m.unidade_id = uid and m.ano = ano and m.mes = meses), 0),
                 (select coalesce(sum(value::int), 0) from jsonb_each_text(u->'atendidas'->meses::text)),
                 u->'atendidas'->meses::text
          on conflict (unidade_id, ano, mes) do update
            set atendidas = excluded.atendidas, atendidas_porte = excluded.atendidas_porte;
          total_atendidas := total_atendidas + 1;
        end if;
      end loop;
    end if;

    insert into public.dim_sincronizacao_sst
      (ano, unidade_id, codigo_api, cobertura, ultima_varredura_em, documentos,
       demanda_gravada, atendidas_gravadas, aplicada, mensagem)
    values (ano, uid, u->>'codigo_api', u->>'cobertura',
            nullif(u->>'ultima_varredura_em', '')::timestamptz,
            greatest(0, coalesce(nullif(u->>'documentos', '')::int, 0)),
            total_demanda, total_atendidas, aplicar, u->>'mensagem');
  end loop;

  return jsonb_build_object('ano', ano, 'unidades', jsonb_array_length(p_payload->'unidades'));
end;
$_$;

revoke all on function public.dim_definir_alocacoes(uuid, jsonb)        from public, anon;
revoke all on function public.dim_substituir_demanda_ano(integer, jsonb, text) from public, anon;
revoke all on function public.dim_aplicar_sincronizacao_sst(jsonb)      from public, anon;
grant execute on function public.dim_definir_alocacoes(uuid, jsonb)              to authenticated;
grant execute on function public.dim_substituir_demanda_ano(integer, jsonb, text) to authenticated;
grant execute on function public.dim_aplicar_sincronizacao_sst(jsonb)            to authenticated;


commit;

-- Sem `notify pgrst, 'reload schema'` de propósito. Com `PGRST_DB_POOL=5` (o valor do
-- painel-sst-postgrest), o reload por NOTIFY já derrubou a API do EAD por 1min30: o
-- PostgREST recarrega o cache do schema ocupando as conexões do pool e as requisições
-- ficam na fila. `docker restart painel-sst-postgrest` custa poucos segundos e é
-- previsível. Quem faz isso é o dim01-apply.sh, que depois sonda uma rota de DADOS —
-- `/api/health` não toca no PostgREST e passaria 200 com o cache velho.
