-- v272 (2026-10-06): Fase 2 da AEP com menos dependência de entrevistas.
--   • psi_biblioteca_fatores — biblioteca única dos 13 fatores psicossociais
--     (chave = a do sistema: assedio, falta_suporte…), com descrição do risco,
--     danos à saúde, fontes geradoras codificadas, meio de propagação,
--     situação/tempo de exposição padrão, sugestões iniciais e ações. Seed do
--     Anexo A do plano. Leitura para autenticados; escrita só Admin.
--     Preparada para o DRPS/QPS usarem depois (sem empresa_id).
--   • aep_relatorios.checklist_gestao — checklist de gestão por AEP
--     (G01–G26, catálogo em lib/aep/checklist-gestao.ts).
-- Idempotente: o seed não sobrescreve o que o Admin já editou.
-- Já aplicada via MCP. Rollback: scripts/sql/v272_rollback_biblioteca_psi_checklist_gestao.sql

create table if not exists public.psi_biblioteca_fatores (
  fator text primary key,
  ordem int not null,
  descricao_risco text not null default '',
  danos_saude text not null default '',
  meio_propagacao text not null default '',
  situacao_padrao text not null default '',
  tempo_exposicao_padrao text not null default '',
  medidas_controle_verificar text not null default '',
  fontes_geradoras jsonb not null default '[]'::jsonb,
  sugestoes_iniciais jsonb not null default '[]'::jsonb,
  acoes jsonb not null default '[]'::jsonb,
  atualizado_em timestamptz not null default now(),
  atualizado_por text
);

alter table public.psi_biblioteca_fatores enable row level security;

drop policy if exists "autenticado le psi_biblioteca_fatores" on public.psi_biblioteca_fatores;
create policy "autenticado le psi_biblioteca_fatores" on public.psi_biblioteca_fatores
  for select to authenticated using (true);

drop policy if exists "admin grava psi_biblioteca_fatores" on public.psi_biblioteca_fatores;
create policy "admin grava psi_biblioteca_fatores" on public.psi_biblioteca_fatores
  for all to authenticated using (public.caller_eh_admin()) with check (public.caller_eh_admin());

alter table public.aep_relatorios add column if not exists checklist_gestao jsonb not null default '{}'::jsonb;

insert into public.psi_biblioteca_fatores
  (fator, ordem, descricao_risco, danos_saude, meio_propagacao, situacao_padrao, tempo_exposicao_padrao,
   medidas_controle_verificar, fontes_geradoras, sugestoes_iniciais, acoes)
values
  ('assedio', 1, 'Exposição a condutas abusivas, repetitivas ou pontuais, praticadas por superiores, colegas ou terceiros, como humilhações, constrangimentos, intimidações, cobranças vexatórias e desrespeito, que atentam contra a dignidade e a integridade psíquica do trabalhador e degradam o ambiente de trabalho.', 'Estresse, ansiedade, depressão, síndrome de burnout, transtorno de estresse pós-traumático, distúrbios do sono, queda da autoestima, sintomas psicossomáticos (cefaleia, distúrbios gastrointestinais) e, em casos graves, ideação suicida.', 'Relações interpessoais e práticas de gestão', 'Normal', 'Habitual e permanente',
   'A verificar em campo: política de prevenção ao assédio; canal de denúncia sigiloso; procedimento de apuração; capacitação de lideranças; ações da CIPA sobre prevenção ao assédio (NR-05 / Lei 14.457/2022).',
   '[{"codigo": "1.1", "texto": "Ausência de política formal de prevenção e enfrentamento ao assédio e às demais formas de violência no trabalho"}, {"codigo": "1.2", "texto": "Inexistência ou ineficácia de canal de denúncia com sigilo e garantia de não retaliação"}, {"codigo": "1.3", "texto": "Ausência de procedimento de apuração de denúncias e de aplicação de medidas"}, {"codigo": "1.4", "texto": "Estilo de gestão autoritário ou baseado em intimidação"}, {"codigo": "1.5", "texto": "Lideranças sem capacitação em gestão de pessoas, comunicação e feedback"}, {"codigo": "1.6", "texto": "Cultura organizacional que tolera ou naturaliza condutas desrespeitosas"}, {"codigo": "1.7", "texto": "Gestão de desempenho com exposição pública de resultados individuais"}]'::jsonb,
   '["Elaborar e divulgar política de prevenção e enfrentamento ao assédio", "Implantar canal de denúncia com sigilo e garantia de não retaliação", "Orientar as lideranças sobre condutas vedadas e cobranças adequadas", "Incluir o tema nas ações da CIPA"]'::jsonb,
   '["Formalizar procedimento de recebimento, apuração e resposta a denúncias", "Capacitar periodicamente as lideranças em gestão de pessoas, feedback e comunicação não violenta", "Realizar ações anuais de capacitação sobre assédio para todos os empregados", "Instituir código de conduta", "Monitorar indicadores (denúncias, afastamentos, rotatividade)"]'::jsonb),
  ('falta_suporte', 2, 'Insuficiência de apoio técnico, emocional e organizacional da liderança, do RH e dos colegas para a realização do trabalho e o enfrentamento de dificuldades, deixando o trabalhador sem orientação, acolhimento ou recursos para resolver problemas.', 'Estresse, ansiedade, sentimento de desamparo e insegurança, desmotivação, síndrome de burnout e aumento de erros e acidentes.', 'Organização do trabalho e práticas de gestão', 'Normal', 'Habitual e permanente',
   'A verificar em campo: rotinas de acompanhamento pela liderança; canal para reporte de dificuldades; programa de integração; atuação do RH em relações de trabalho.',
   '[{"codigo": "2.1", "texto": "Liderança com número excessivo de subordinados ou acúmulo de funções, o que limita sua disponibilidade"}, {"codigo": "2.2", "texto": "Ausência de rotinas estruturadas de acompanhamento (reuniões de alinhamento, conversas individuais)"}, {"codigo": "2.3", "texto": "RH com atuação restrita a processos administrativos, sem atuação em desenvolvimento e relações de trabalho"}, {"codigo": "2.4", "texto": "Ausência de canal formal para reporte de dificuldades e problemas operacionais"}, {"codigo": "2.5", "texto": "Ausência de referência técnica definida para as atividades"}, {"codigo": "2.6", "texto": "Tratamento de erros com foco punitivo, sem análise de causa e orientação"}, {"codigo": "2.7", "texto": "Ausência de programa de integração e acompanhamento de novos colaboradores"}]'::jsonb,
   '["Instituir reuniões periódicas de alinhamento com a equipe", "Definir referência técnica para cada atividade", "Divulgar formas de acesso ao RH e à liderança"]'::jsonb,
   '["Implantar rotina de conversas individuais periódicas entre líder e liderado", "Revisar o número de subordinados e as atribuições das lideranças", "Estruturar programa de integração e acompanhamento de novos colaboradores", "Adotar análise de causa dos erros, com abordagem orientativa e não punitiva", "Ampliar a atuação do RH em desenvolvimento e relações de trabalho"]'::jsonb),
  ('gestao_mudancas', 3, 'Implantação de mudanças organizacionais (estrutura, processos, tecnologias, quadro de pessoal ou lideranças) sem planejamento, comunicação adequada e participação dos trabalhadores, gerando incerteza, insegurança e retrabalho.', 'Estresse, ansiedade, insegurança quanto ao emprego, distúrbios do sono, desmotivação e síndrome de burnout.', 'Processos de gestão e comunicação organizacional', 'Normal', 'Intermitente (durante processos de mudança)',
   'A verificar em campo: procedimento de gestão de mudanças; registros de comunicação formal das mudanças; capacitações associadas.',
   '[{"codigo": "3.1", "texto": "Ausência de procedimento formal de gestão de mudanças"}, {"codigo": "3.2", "texto": "Comunicação das mudanças não planejada, tardia ou restrita a parte da equipe"}, {"codigo": "3.3", "texto": "Ausência de consulta ou participação dos trabalhadores afetados"}, {"codigo": "3.4", "texto": "Mudanças implementadas sem cronograma, responsáveis e período de transição definidos"}, {"codigo": "3.5", "texto": "Ausência de capacitação para novos processos, sistemas ou funções"}, {"codigo": "3.6", "texto": "Reestruturações sem redefinição formal de funções e responsabilidades"}, {"codigo": "3.7", "texto": "Ausência de canal para esclarecimento de dúvidas durante a transição"}]'::jsonb,
   '["Comunicar formalmente as mudanças antes da implantação", "Disponibilizar canal para esclarecimento de dúvidas", "Envolver os trabalhadores afetados no planejamento"]'::jsonb,
   '["Estabelecer procedimento de gestão de mudanças com avaliação prévia dos impactos em SST, com reavaliação dos riscos conforme a NR-01", "Definir cronograma, responsáveis e período de transição para cada mudança", "Capacitar os trabalhadores antes da implantação de novos processos ou sistemas", "Revisar descrições de cargo após reestruturações"]'::jsonb),
  ('clareza_papel', 4, 'Indefinição ou ambiguidade quanto às atribuições, responsabilidades, autoridade e resultados esperados, incluindo instruções conflitantes e subordinação a mais de uma chefia.', 'Estresse, ansiedade, frustração, conflitos interpessoais, retrabalho, aumento de erros e síndrome de burnout.', 'Organização do trabalho', 'Normal', 'Habitual e permanente',
   'A verificar em campo: descrição de cargos; organograma divulgado; POPs/ITs; fluxo de repasse de instruções.',
   '[{"codigo": "4.1", "texto": "Ausência de descrição formal de cargos e atribuições"}, {"codigo": "4.2", "texto": "Estrutura hierárquica não definida ou não divulgada (organograma)"}, {"codigo": "4.3", "texto": "Sobreposição de chefias (duplo comando)"}, {"codigo": "4.4", "texto": "Ausência de procedimentos operacionais padronizados (POP/IT)"}, {"codigo": "4.5", "texto": "Ausência de fluxo formal para repasse de instruções"}, {"codigo": "4.6", "texto": "Integração inicial insuficiente quanto às atribuições do cargo"}, {"codigo": "4.7", "texto": "Acúmulo ou desvio de funções não formalizado"}]'::jsonb,
   '["Divulgar o organograma às equipes", "Definir uma única chefia de referência para cada trabalhador", "Padronizar o repasse de instruções"]'::jsonb,
   '["Elaborar ou revisar as descrições de cargo e entregá-las formalmente", "Elaborar POPs/ITs para as atividades críticas", "Formalizar o fluxo de repasse de instruções", "Revisar o conteúdo da integração quanto às atribuições do cargo", "Formalizar ou eliminar acúmulos e desvios de função"]'::jsonb),
  ('recompensas', 5, 'Desequilíbrio entre o esforço exigido do trabalhador e as recompensas recebidas, como remuneração, reconhecimento, feedback e oportunidades de desenvolvimento e crescimento.', 'Desmotivação, estresse, ansiedade, depressão, insatisfação com o trabalho e síndrome de burnout.', 'Políticas de gestão de pessoas', 'Normal', 'Habitual e permanente',
   'A verificar em campo: plano de cargos e salários; avaliação de desempenho; práticas de reconhecimento; plano de capacitação.',
   '[{"codigo": "5.1", "texto": "Ausência de plano de cargos, carreira e salários"}, {"codigo": "5.2", "texto": "Ausência de processo estruturado de avaliação de desempenho e feedback"}, {"codigo": "5.3", "texto": "Inexistência de práticas de reconhecimento, formais ou informais"}, {"codigo": "5.4", "texto": "Critérios de promoção e remuneração variável não definidos ou não divulgados"}, {"codigo": "5.5", "texto": "Metas focadas exclusivamente em resultado, sem considerar esforço e condições de trabalho"}, {"codigo": "5.6", "texto": "Ausência de programa de desenvolvimento e capacitação profissional"}]'::jsonb,
   '["Instituir feedback periódico, e não apenas diante de erros", "Reconhecer formalmente bons resultados e esforços", "Divulgar os critérios de promoção existentes"]'::jsonb,
   '["Implantar processo estruturado de avaliação de desempenho", "Elaborar plano de cargos, carreira e salários", "Instituir programa de reconhecimento", "Elaborar plano anual de capacitação e desenvolvimento", "Revisar as metas, considerando esforço e condições de trabalho"]'::jsonb),
  ('baixo_controle', 6, 'Pouca possibilidade de o trabalhador influenciar o modo, o ritmo, a ordem e os métodos de execução das tarefas e de participar das decisões relacionadas ao próprio trabalho.', 'Estresse, ansiedade, desmotivação, sentimento de desvalorização, síndrome de burnout e maior risco de doenças cardiovasculares quando associado a altas demandas.', 'Organização do trabalho e modelo de gestão', 'Normal', 'Habitual e permanente',
   'A verificar em campo: alçadas de decisão definidas; mecanismos de participação dos trabalhadores; tratamento dado aos erros.',
   '[{"codigo": "6.1", "texto": "Centralização das decisões em poucos níveis hierárquicos"}, {"codigo": "6.2", "texto": "Modelo de gestão baseado em controle detalhado (microgerenciamento)"}, {"codigo": "6.3", "texto": "Ausência de delegação formal e de alçadas de decisão definidas"}, {"codigo": "6.4", "texto": "Métodos e ritmo de trabalho impostos sem participação dos trabalhadores"}, {"codigo": "6.5", "texto": "Ausência de participação dos trabalhadores no planejamento das atividades"}, {"codigo": "6.6", "texto": "Cultura punitiva em relação ao erro"}, {"codigo": "6.7", "texto": "Ausência de capacitação para atuação autônoma"}]'::jsonb,
   '["Definir o que cada função pode decidir sem consulta prévia", "Ouvir a equipe antes de decisões que afetam o trabalho"]'::jsonb,
   '["Formalizar delegação e alçadas de decisão", "Implementar mecanismos de participação (reuniões de equipe, programa de sugestões)", "Capacitar as equipes para atuação autônoma", "Revisar o modelo de supervisão, reduzindo controles e revisões excessivos", "Tratar os erros como oportunidade de aprendizado"]'::jsonb),
  ('justica_organizacional', 7, 'Percepção de falta de imparcialidade, transparência e coerência nas decisões, na distribuição de tarefas, recursos e benefícios e na aplicação de regras e punições.', 'Estresse, ansiedade, depressão, desmotivação, sentimento de injustiça, conflitos interpessoais e síndrome de burnout.', 'Processos decisórios e práticas de gestão', 'Normal', 'Habitual e permanente',
   'A verificar em campo: critérios formais de decisão; transparência na comunicação; canal de contestação.',
   '[{"codigo": "7.1", "texto": "Critérios de decisão não definidos ou não divulgados (escalas, folgas, distribuição de tarefas, promoções, punições)"}, {"codigo": "7.2", "texto": "Ausência de transparência na comunicação das decisões"}, {"codigo": "7.3", "texto": "Aplicação desigual de regras e políticas internas"}, {"codigo": "7.4", "texto": "Ausência de canal para contestação ou revisão de decisões"}, {"codigo": "7.5", "texto": "Relações pessoais influenciando decisões de gestão"}, {"codigo": "7.6", "texto": "Ausência de procedimento para gestão de conflitos"}]'::jsonb,
   '["Comunicar os critérios utilizados nas decisões", "Aplicar as regras de forma uniforme a todos"]'::jsonb,
   '["Formalizar e divulgar critérios para escalas, folgas, distribuição de tarefas, promoções e punições", "Implantar canal para contestação ou revisão de decisões", "Estabelecer procedimento de gestão de conflitos", "Capacitar as lideranças em tomada de decisão imparcial"]'::jsonb),
  ('eventos_traumaticos', 8, 'Possibilidade de exposição a agressões verbais ou físicas, ameaças, assaltos ou outros eventos traumáticos, praticados por clientes, público ou terceiros, ou presenciados durante o trabalho.', 'Transtorno de estresse agudo, transtorno de estresse pós-traumático, ansiedade, depressão, fobias, distúrbios do sono e lesões físicas em caso de agressão.', 'Contato direto com público ou terceiros e ambiente externo', 'Normal e emergência', 'Eventual',
   'A verificar em campo: protocolos de segurança e de resposta a incidentes; treinamento em manejo de conflitos; medidas de segurança patrimonial; registro de ocorrências.',
   '[{"codigo": "8.1", "texto": "Atividade com atendimento ao público em situações potencialmente conflituosas (cobranças, reclamações, negativas)"}, {"codigo": "8.2", "texto": "Atividade com exposição a violência externa (manuseio de valores, trabalho noturno, locais com histórico de ocorrências)"}, {"codigo": "8.3", "texto": "Ausência de protocolos de segurança e de resposta a incidentes"}, {"codigo": "8.4", "texto": "Ausência de treinamento em manejo de conflitos e situações de risco"}, {"codigo": "8.5", "texto": "Medidas de segurança patrimonial inexistentes ou inadequadas"}, {"codigo": "8.6", "texto": "Ausência de registro e investigação de incidentes de violência"}, {"codigo": "8.7", "texto": "Ausência de suporte psicológico após eventos"}]'::jsonb,
   '["Elaborar protocolo de conduta para situações de conflito ou violência", "Registrar todas as ocorrências, inclusive as informais"]'::jsonb,
   '["Treinar os trabalhadores em manejo de conflitos e situações de risco", "Implantar medidas de segurança patrimonial (controle de acesso, CFTV, botão de pânico, conforme o caso)", "Estabelecer procedimento de resposta a incidentes, incluindo emissão de CAT quando aplicável", "Disponibilizar suporte psicológico após eventos", "Investigar os incidentes e revisar as medidas"]'::jsonb),
  ('subcarga', 9, 'Volume de trabalho, conteúdo das tarefas ou exigência cognitiva insuficientes ou incompatíveis com a qualificação do trabalhador, incluindo períodos ociosos frequentes e tarefas monótonas.', 'Tédio, desmotivação, ansiedade, sentimento de inutilidade, redução da atenção (com aumento de erros e acidentes) e depressão.', 'Organização do trabalho (conteúdo e distribuição das tarefas)', 'Normal', 'Habitual e intermitente',
   'A verificar em campo: planejamento e distribuição das demandas; rodízio de tarefas; adequação entre função e qualificação.',
   '[{"codigo": "9.1", "texto": "Planejamento e distribuição inadequados das demandas entre colaboradores e setores"}, {"codigo": "9.2", "texto": "Variação sazonal da produção sem realocação de pessoal"}, {"codigo": "9.3", "texto": "Dimensionamento de quadro acima da demanda"}, {"codigo": "9.4", "texto": "Alocação de profissionais em funções incompatíveis com sua qualificação"}, {"codigo": "9.5", "texto": "Tarefas fragmentadas, repetitivas e de baixo conteúdo"}, {"codigo": "9.6", "texto": "Ausência de rodízio ou de enriquecimento de tarefas"}, {"codigo": "9.7", "texto": "Tempos de espera por dependência de etapas anteriores, insumos ou sistemas"}]'::jsonb,
   '["Redistribuir as demandas entre trabalhadores e setores", "Aproveitar períodos ociosos para capacitação"]'::jsonb,
   '["Revisar o planejamento e a distribuição das demandas", "Implantar rodízio e enriquecimento de tarefas", "Adequar a alocação dos profissionais à sua qualificação", "Elaborar plano de ação para períodos de baixa produção", "Revisar o dimensionamento do quadro"]'::jsonb),
  ('sobrecarga', 10, 'Volume de trabalho, ritmo, prazos ou metas superiores à capacidade do trabalhador ou da equipe dentro da jornada, com acúmulo de atividades e sensação de urgência permanente.', 'Estresse, fadiga física e mental, ansiedade, distúrbios do sono, síndrome de burnout, LER/DORT associadas a ritmo intenso, hipertensão arterial e doenças cardiovasculares, além de aumento de acidentes.', 'Organização do trabalho (volume, ritmo, prazos e metas)', 'Normal', 'Habitual e permanente',
   'A verificar em campo: dimensionamento do quadro; controle de jornada e horas extras; critérios de definição de metas; cobertura de ausências.',
   '[{"codigo": "10.1", "texto": "Dimensionamento de quadro insuficiente para o volume de trabalho"}, {"codigo": "10.2", "texto": "Acúmulo de funções"}, {"codigo": "10.3", "texto": "Metas e prazos definidos sem considerar a capacidade produtiva"}, {"codigo": "10.4", "texto": "Planejamento deficiente, gerando urgências recorrentes"}, {"codigo": "10.5", "texto": "Ausência de cobertura para ausências (férias, afastamentos, desligamentos)"}, {"codigo": "10.6", "texto": "Jornadas prolongadas ou horas extras habituais"}, {"codigo": "10.7", "texto": "Interrupções frequentes durante a execução das tarefas"}]'::jsonb,
   '["Priorizar as demandas em conjunto com a liderança", "Acompanhar a realização de horas extras"]'::jsonb,
   '["Revisar o dimensionamento do quadro", "Definir metas e prazos com base na capacidade produtiva", "Estabelecer plano de cobertura para férias e afastamentos", "Controlar jornada e horas extras habituais", "Reduzir interrupções durante a execução das tarefas"]'::jsonb),
  ('maus_relacionamentos', 11, 'Relações interpessoais conflituosas, desrespeitosas ou distantes entre colegas e/ou com a liderança, com conflitos não tratados e baixa cooperação.', 'Estresse, ansiedade, irritabilidade, depressão, isolamento social e síndrome de burnout.', 'Relações interpessoais', 'Normal', 'Habitual e permanente',
   'A verificar em campo: procedimento de gestão de conflitos; código de conduta; ações de integração; atuação das lideranças diante de conflitos.',
   '[{"codigo": "11.1", "texto": "Ausência de procedimento para gestão de conflitos"}, {"codigo": "11.2", "texto": "Lideranças que não intervêm em conflitos ou não têm capacitação para isso"}, {"codigo": "11.3", "texto": "Ausência de código de conduta ou de normas de convivência"}, {"codigo": "11.4", "texto": "Organização do trabalho que estimula a competição entre colegas (metas individuais concorrentes)"}, {"codigo": "11.5", "texto": "Ausência de ações de integração entre equipes"}, {"codigo": "11.6", "texto": "Indefinição de responsabilidades, gerando atritos entre colegas"}]'::jsonb,
   '["Orientar as lideranças a intervir precocemente nos conflitos", "Estabelecer normas de convivência com as equipes"]'::jsonb,
   '["Estabelecer procedimento de gestão de conflitos", "Instituir código de conduta", "Capacitar as lideranças em mediação de conflitos", "Promover ações de integração entre equipes", "Revisar metas que estimulam competição entre colegas"]'::jsonb),
  ('comunicacao_dificil', 12, 'Fluxos de informação deficientes, informais ou inexistentes, com informações divergentes, incompletas ou que não chegam a todos, dificultando a execução segura e eficiente do trabalho.', 'Estresse, ansiedade, frustração, conflitos interpessoais e aumento de erros e acidentes.', 'Sistemas e fluxos de comunicação', 'Normal', 'Habitual e permanente',
   'A verificar em campo: canais formais de comunicação; registros de passagem de turno; reuniões de alinhamento; pontos focais definidos.',
   '[{"codigo": "12.1", "texto": "Ausência de canais formais de comunicação"}, {"codigo": "12.2", "texto": "Fluxo de informação não definido (quem informa, a quem e por qual meio)"}, {"codigo": "12.3", "texto": "Ausência de registros e documentação das informações operacionais"}, {"codigo": "12.4", "texto": "Ausência de reuniões de alinhamento ou de passagem de turno"}, {"codigo": "12.5", "texto": "Barreiras físicas ou organizacionais (ruído, distância entre setores, turnos distintos)"}, {"codigo": "12.6", "texto": "Ferramentas e sistemas de comunicação inadequados ou insuficientes"}]'::jsonb,
   '["Definir os canais oficiais de comunicação", "Realizar reuniões curtas de alinhamento ou de passagem de turno"]'::jsonb,
   '["Elaborar matriz de comunicação (quem informa, a quem, quando e por qual meio)", "Implantar registros formais (livro de passagem de turno, quadro de avisos)", "Adequar as ferramentas de comunicação", "Definir pontos focais por setor ou atividade"]'::jsonb),
  ('trabalho_remoto', 13, 'Realização do trabalho fora das instalações da empresa ou em local isolado, com contato reduzido com colegas e liderança, o que dificulta integração, suporte e alinhamento de informações e, no trabalho isolado, o socorro em emergências.', 'Isolamento social, solidão, ansiedade, depressão, estresse, dificuldade de desconexão com prolongamento da jornada e síndrome de burnout; no trabalho isolado, agravamento de lesões por demora no socorro.', 'Organização do trabalho e meios de comunicação à distância', 'Normal e emergência (trabalho isolado)', 'Habitual e permanente',
   'A verificar em campo: política de teletrabalho; rotinas de contato com a equipe; sistema de comunicação e monitoramento do trabalhador isolado; protocolo de emergência.',
   '[{"codigo": "13.1", "texto": "Ausência de política de teletrabalho (rotinas, disponibilidade, direito à desconexão)"}, {"codigo": "13.2", "texto": "Ausência de rotinas de contato síncrono com a equipe e a liderança"}, {"codigo": "13.3", "texto": "Ausência de ações de integração para trabalhadores remotos"}, {"codigo": "13.4", "texto": "Ferramentas de comunicação inadequadas"}, {"codigo": "13.5", "texto": "Trabalho em local fisicamente isolado, sem contato regular com outras pessoas"}, {"codigo": "13.6", "texto": "Ausência de sistema de comunicação e monitoramento para trabalhador isolado"}, {"codigo": "13.7", "texto": "Ausência de protocolo de emergência para trabalho isolado"}]'::jsonb,
   '["Estabelecer rotina de contato síncrono com a equipe", "Instituir check-in periódico para trabalhadores isolados"]'::jsonb,
   '["Elaborar política de teletrabalho (CLT, art. 75-A e seguintes), incluindo direito à desconexão", "Promover ações periódicas de integração", "Disponibilizar ferramentas de comunicação adequadas", "Implantar sistema de comunicação e monitoramento para trabalho isolado", "Estabelecer protocolo de emergência para trabalho isolado"]'::jsonb)
on conflict (fator) do nothing;
